// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-15T00:50:32.670Z

package creditcard

import (
    _ "embed"
    "encoding/json"
    "sync"
)

//go:embed cards-detailed.json
var cardsDetailedJSON []byte

// Pattern represents a BIN pattern for validation
type Pattern struct {
    Bin       string `json:"bin"`
    Length    []int  `json:"length"`
    Luhn      bool   `json:"luhn"`
    CvvLength int    `json:"cvvLength"`
}

// BinInfo represents detailed BIN information
type BinInfo struct {
    Bin       string   `json:"bin"`
    Type      string   `json:"type"`
    Category  string   `json:"category"`
    Issuer    string   `json:"issuer"`
    Countries []string `json:"countries"`
}

// NumberInfo represents card number validation info
type NumberInfo struct {
    Lengths []int `json:"lengths"`
    Luhn    bool  `json:"luhn"`
}

// CvvInfo represents CVV validation info
type CvvInfo struct {
    Length int `json:"length"`
}

// BrandDetailed represents detailed credit card brand information
type BrandDetailed struct {
    Scheme       string                 `json:"scheme"`
    Brand        string                 `json:"brand"`
    Type         string                 `json:"type"`
    Number       NumberInfo             `json:"number"`
    Cvv          CvvInfo                `json:"cvv"`
    Patterns     []Pattern              `json:"patterns"`
    Countries    []string               `json:"countries"`
    Metadata     map[string]interface{} `json:"metadata"`
    PriorityOver []string               `json:"priorityOver"`
    Bins         []BinInfo              `json:"bins"`
}

var (
    brandsDetailedOnce sync.Once
    brandsDetailedData []BrandDetailed
)

// GetBrandsDetailed returns detailed information about all supported brands (lazy-loaded from JSON)
func GetBrandsDetailed() []BrandDetailed {
    brandsDetailedOnce.Do(func() {
        if err := json.Unmarshal(cardsDetailedJSON, &brandsDetailedData); err != nil {
            panic("failed to parse cards-detailed.json: " + err.Error())
        }
    })
    return brandsDetailedData
}

// BrandsDetailed is deprecated. Use GetBrandsDetailed() instead.
var BrandsDetailed = []BrandDetailed{}
