// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-12T09:52:15.511Z

package creditcard

// Pattern represents a BIN pattern for validation
type Pattern struct {
    Bin       string
    Length    []int
    Luhn      bool
    CvvLength int
}

// BinInfo represents detailed BIN information
type BinInfo struct {
    Bin       string
    Type      string
    Category  string
    Issuer    string
    Countries []string
}

// BrandDetailed represents detailed credit card brand information
type BrandDetailed struct {
    Scheme        string
    Brand         string
    Type          string
    NumberLengths []int
    NumberLuhn    bool
    CvvLength     int
    Patterns      []Pattern
    Countries     []string
    Metadata      map[string]interface{}
    PriorityOver  []string
    Bins          []BinInfo
}

// BrandsDetailed contains detailed information about all supported brands
var BrandsDetailed = []BrandDetailed{
    {
        Scheme:        "amex",
        Brand:         "American Express",
        Type:          "credit",
        NumberLengths: []int{15},
        NumberLuhn:    true,
        CvvLength:     4,
        Patterns: []Pattern{
            {
                Bin:       "^3[47]",
                Length:    []int{15},
                Luhn:      true,
                CvvLength: 4,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "amex.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "diners",
        Brand:         "Diners Club",
        Type:          "credit",
        NumberLengths: []int{14},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^3(?:0[0-5]|[68][0-9])",
                Length:    []int{14},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "diners.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "elo",
        Brand:         "Elo",
        Type:          "credit",
        NumberLengths: []int{16},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^401178|^401179|^431274|^438935|^451416|^457393|^457631|^457632|^504175",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^627780|^636297|^636368",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(506699|5067[0-6]\\d|50677[0-8])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^65003[1-3]",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65003[5-9]|65004\\d|65005[0-1])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65040[5-9]|6504[1-3]\\d)",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65054[1-9]|6505[5-8]\\d|65059[0-8])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65070\\d|65071[0-8])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6507(2[0-7])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6509[0-9]",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65165[2-9]|6516[6-7]\\d)",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65500\\d|65501\\d)",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^(65502[1-9]|6550[3-4]\\d|65505[0-8])",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"BR"},
        Metadata: map[string]interface{}{
            "sourceFile": "elo.json",
        },
        PriorityOver: []string{"visa", "aura", "discover", "banesecard"},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "jcb",
        Brand:         "JCB",
        Type:          "credit",
        NumberLengths: []int{16},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^(?:2131|1800|35)",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "jcb.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "mastercard",
        Brand:         "Mastercard",
        Type:          "credit",
        NumberLengths: []int{16},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^5[1-5]",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^2[2-7][0-2][0-9]",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "mastercard.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "aura",
        Brand:         "Aura",
        Type:          "credit",
        NumberLengths: []int{16, 17, 18, 19},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^50",
                Length:    []int{16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"BR"},
        Metadata: map[string]interface{}{
            "sourceFile": "aura.json",
        },
        PriorityOver: []string{"maestro"},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "banesecard",
        Brand:         "BaneseCard",
        Type:          "credit",
        NumberLengths: []int{16},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^636117",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^637473",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^637470",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^637472",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^650725",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^650046",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^650591",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^651668",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^651679",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"BR"},
        Metadata: map[string]interface{}{
            "sourceFile": "banesecard.json",
        },
        PriorityOver: []string{"discover"},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "maestro",
        Brand:         "Maestro",
        Type:          "debit",
        NumberLengths: []int{12, 13, 14, 15, 16, 17, 18, 19},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^5018",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^5020",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^5038",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^5893",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6304",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6759",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^676[1-3]",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6706",
                Length:    []int{12, 13, 14, 15, 16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "maestro.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "visa",
        Brand:         "Visa",
        Type:          "credit",
        NumberLengths: []int{13, 16},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^4",
                Length:    []int{13, 16},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^6367",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": []string{"visa/base.json", "visa/bins-br-1.json", "visa/bins-br-2.json"},
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
            {
                Bin:       "491441",
                Type:      "CREDIT",
                Category:  "",
                Issuer:    "BANCO PROSPER, S.A.",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491440",
                Type:      "CREDIT",
                Category:  "",
                Issuer:    "BANCO PROSPER, S.A.",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491439",
                Type:      "CREDIT",
                Category:  "",
                Issuer:    "BANCO PROSPER, S.A.",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491423",
                Type:      "CREDIT",
                Category:  "",
                Issuer:    "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491416",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO DO ESTADO DO PARANA",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491415",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO DO ESTADO DO PARANA",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491414",
                Type:      "CREDIT",
                Category:  "GOLD",
                Issuer:    "BANCO DO ESTADO DO PARANA",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491413",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                Countries: []string{"BR"},
            },
            {
                Bin:       "491412",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                Countries: []string{},
            },
            {
                Bin:       "491411",
                Type:      "CREDIT",
                Category:  "GOLD",
                Issuer:    "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                Countries: []string{},
            },
            {
                Bin:       "491402",
                Type:      "CREDIT",
                Category:  "",
                Issuer:    "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                Countries: []string{},
            },
            {
                Bin:       "491316",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO SANTANDER BRASIL, S.A.",
                Countries: []string{},
            },
            {
                Bin:       "491315",
                Type:      "CREDIT",
                Category:  "CLASSIC",
                Issuer:    "BANCO SANTANDER, S.A.",
                Countries: []string{},
            },
            {
                Bin:       "491314",
                Type:      "CREDIT",
                Category:  "GOLD",
                Issuer:    "BANCO SANTANDER, S.A.",
                Countries: []string{},
            },
            {
                Bin:       "491256",
                Type:      "CREDIT",
                Category:  "PLATINUM",
                Issuer:    "BANCO PANAMERICANO, S.A.",
                Countries: []string{},
            },
        },
    },
    {
        Scheme:        "discover",
        Brand:         "Discover",
        Type:          "credit",
        NumberLengths: []int{16, 19},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^6011",
                Length:    []int{16, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^64[4-9]",
                Length:    []int{16, 19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^65",
                Length:    []int{16, 19},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"US"},
        Metadata: map[string]interface{}{
            "sourceFile": "discover.json",
        },
        PriorityOver: []string{"hipercard", "unionpay"},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "hipercard",
        Brand:         "Hipercard",
        Type:          "credit",
        NumberLengths: []int{16, 19},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^38",
                Length:    []int{19},
                Luhn:      true,
                CvvLength: 3,
            },
            {
                Bin:       "^60",
                Length:    []int{16},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"BR"},
        Metadata: map[string]interface{}{
            "sourceFile": "hipercard.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
    {
        Scheme:        "unionpay",
        Brand:         "UnionPay",
        Type:          "debit",
        NumberLengths: []int{16, 17, 18, 19},
        NumberLuhn:    true,
        CvvLength:     3,
        Patterns: []Pattern{
            {
                Bin:       "^62",
                Length:    []int{16, 17, 18, 19},
                Luhn:      true,
                CvvLength: 3,
            },
        },
        Countries: []string{"CN", "GLOBAL"},
        Metadata: map[string]interface{}{
            "sourceFile": "unionpay.json",
        },
        PriorityOver: []string{},
        Bins: []BinInfo{
        },
    },
}
