// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-13T23:49:54.659Z

package creditcard

// Brand represents a credit card brand with validation patterns
type Brand struct {
    Name         string
    PriorityOver []string
    RegexpBin    string
    RegexpFull   string
    RegexpCvv    string
}

// Brands contains all supported credit card brands
var Brands = []Brand{
    {
        Name:         "amex",
        PriorityOver: []string{},
        RegexpBin:    "^(3[47])",
        RegexpFull:   "^(?=.{15}$)(?:3[47])[0-9]*$",
        RegexpCvv:    "^\\d{4}$",
    },
    {
        Name:         "diners",
        PriorityOver: []string{},
        RegexpBin:    "^(3(?:0[0-5]|[68][0-9]))",
        RegexpFull:   "^(?=.{14}$)(?:3(?:0[0-5]|[68][0-9]))[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "elo",
        PriorityOver: []string{"visa", "aura", "discover", "banesecard"},
        RegexpBin:    "^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))",
        RegexpFull:   "^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "jcb",
        PriorityOver: []string{},
        RegexpBin:    "^((?:2131|1800|35))",
        RegexpFull:   "^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "mastercard",
        PriorityOver: []string{},
        RegexpBin:    "^(5[1-5]|2[2-7][0-2][0-9])",
        RegexpFull:   "^(?=.{16}$)(?:5[1-5]|2[2-7][0-2][0-9])[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "aura",
        PriorityOver: []string{"maestro"},
        RegexpBin:    "^(50)",
        RegexpFull:   "^(?=.{16,19}$)(?:50)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "banesecard",
        PriorityOver: []string{"discover"},
        RegexpBin:    "^(636117|637473|637470|637472|650725|650046|650591|651668|651679)",
        RegexpFull:   "^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "maestro",
        PriorityOver: []string{},
        RegexpBin:    "^(5018|5020|5038|5893|6304|6759|676[1-3]|6706)",
        RegexpFull:   "^(?=.{12,19}$)(?:5018|5020|5038|5893|6304|6759|676[1-3]|6706)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "visa",
        PriorityOver: []string{},
        RegexpBin:    "^(4|6367)",
        RegexpFull:   "^(?=.{13,16}$)(?:4|6367)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "discover",
        PriorityOver: []string{"hipercard", "unionpay"},
        RegexpBin:    "^(6011|64[4-9]|65)",
        RegexpFull:   "^(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "hipercard",
        PriorityOver: []string{},
        RegexpBin:    "^(38|60)",
        RegexpFull:   "^(?=.{16,19}$)(?:38|60)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
    {
        Name:         "unionpay",
        PriorityOver: []string{},
        RegexpBin:    "^(62)",
        RegexpFull:   "^(?=.{16,19}$)(?:62)[0-9]*$",
        RegexpCvv:    "^\\d{3}$",
    },
}
