// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-13T23:04:02.279Z

package br.com.s2n.creditcard.identifier;

import java.util.ArrayList;
import java.util.List;

/**
 * Credit card brand data (simplified).
 */
public class BrandData {

    public static class Brand {
        public final String name;
        public final String[] priorityOver;
        public final String regexpBin;
        public final String regexpFull;
        public final String regexpCvv;

        public Brand(String name, String[] priorityOver, String regexpBin, String regexpFull, String regexpCvv) {
            this.name = name;
            this.priorityOver = priorityOver;
            this.regexpBin = regexpBin;
            this.regexpFull = regexpFull;
            this.regexpCvv = regexpCvv;
        }
    }

    public static final List<Brand> BRANDS = new ArrayList<Brand>() {{
        add(new Brand("amex", new String[0], "^(3[47])", "^(?=.{15}$)(?:3[47])[0-9]*$", "^\\d{4}$"));
        add(new Brand("diners", new String[0], "^(3(?:0[0-5]|[68][0-9]))", "^(?=.{14}$)(?:3(?:0[0-5]|[68][0-9]))[0-9]*$", "^\\d{3}$"));
        add(new Brand("elo", new String[] { "visa", "aura", "discover", "banesecard" }, "^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))", "^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))[0-9]*$", "^\\d{3}$"));
        add(new Brand("jcb", new String[0], "^((?:2131|1800|35))", "^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$", "^\\d{3}$"));
        add(new Brand("mastercard", new String[0], "^(5[1-5]|2[2-7][0-2][0-9])", "^(?=.{16}$)(?:5[1-5]|2[2-7][0-2][0-9])[0-9]*$", "^\\d{3}$"));
        add(new Brand("aura", new String[] { "maestro" }, "^(50)", "^(?=.{16,19}$)(?:50)[0-9]*$", "^\\d{3}$"));
        add(new Brand("banesecard", new String[] { "discover" }, "^(636117|637473|637470|637472|650725|650046|650591|651668|651679)", "^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$", "^\\d{3}$"));
        add(new Brand("maestro", new String[0], "^(5018|5020|5038|5893|6304|6759|676[1-3]|6706)", "^(?=.{12,19}$)(?:5018|5020|5038|5893|6304|6759|676[1-3]|6706)[0-9]*$", "^\\d{3}$"));
        add(new Brand("visa", new String[0], "^(4|6367)", "^(?=.{13,16}$)(?:4|6367)[0-9]*$", "^\\d{3}$"));
        add(new Brand("discover", new String[] { "hipercard", "unionpay" }, "^(6011|64[4-9]|65)", "^(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*$", "^\\d{3}$"));
        add(new Brand("hipercard", new String[0], "^(38|60)", "^(?=.{16,19}$)(?:38|60)[0-9]*$", "^\\d{3}$"));
        add(new Brand("unionpay", new String[0], "^(62)", "^(?=.{16,19}$)(?:62)[0-9]*$", "^\\d{3}$"));
    }};
}
