// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-12T09:59:23.123Z

package br.com.s2n.creditcard.identifier;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Credit card brand data (detailed).
 */
public class BrandDataDetailed {

    public static class Pattern {
        public final String bin;
        public final int[] length;
        public final boolean luhn;
        public final int cvvLength;

        public Pattern(String bin, int[] length, boolean luhn, int cvvLength) {
            this.bin = bin;
            this.length = length;
            this.luhn = luhn;
            this.cvvLength = cvvLength;
        }
    }

    public static class Bin {
        public final String bin;
        public final String type;
        public final String category;
        public final String issuer;
        public final String[] countries;

        public Bin(String bin, String type, String category, String issuer, String[] countries) {
            this.bin = bin;
            this.type = type;
            this.category = category;
            this.issuer = issuer;
            this.countries = countries;
        }
    }

    public static class BrandDetailed {
        public final String scheme;
        public final String brand;
        public final String type;
        public final int[] numberLengths;
        public final boolean numberLuhn;
        public final int cvvLength;
        public final List<Pattern> patterns;
        public final String[] countries;
        public final Map<String, Object> metadata;
        public final String[] priorityOver;
        public final List<Bin> bins;

        public BrandDetailed(String scheme, String brand, String type, int[] numberLengths, boolean numberLuhn,
                            int cvvLength, List<Pattern> patterns, String[] countries, Map<String, Object> metadata,
                            String[] priorityOver, List<Bin> bins) {
            this.scheme = scheme;
            this.brand = brand;
            this.type = type;
            this.numberLengths = numberLengths;
            this.numberLuhn = numberLuhn;
            this.cvvLength = cvvLength;
            this.patterns = patterns;
            this.countries = countries;
            this.metadata = metadata;
            this.priorityOver = priorityOver;
            this.bins = bins;
        }
    }

    public static final List<BrandDetailed> BRANDS = new ArrayList<BrandDetailed>() {{
        List<Pattern> patterns0 = new ArrayList<Pattern>() {{
            add(new Pattern("^3[47]", new int[] { 15 }, true, 4));
        }};
        List<Bin> bins0 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata0 = new HashMap<>();
        metadata0.put("sourceFile", "amex.json");
        add(new BrandDetailed("amex", "American Express", "credit", new int[] { 15 }, true, 4, patterns0, new String[] { "GLOBAL" }, metadata0, new String[0], bins0));
        List<Pattern> patterns1 = new ArrayList<Pattern>() {{
            add(new Pattern("^3(?:0[0-5]|[68][0-9])", new int[] { 14 }, true, 3));
        }};
        List<Bin> bins1 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata1 = new HashMap<>();
        metadata1.put("sourceFile", "diners.json");
        add(new BrandDetailed("diners", "Diners Club", "credit", new int[] { 14 }, true, 3, patterns1, new String[] { "GLOBAL" }, metadata1, new String[0], bins1));
        List<Pattern> patterns2 = new ArrayList<Pattern>() {{
            add(new Pattern("^401178|^401179|^431274|^438935|^451416|^457393|^457631|^457632|^504175", new int[] { 16 }, true, 3));
            add(new Pattern("^627780|^636297|^636368", new int[] { 16 }, true, 3));
            add(new Pattern("^(506699|5067[0-6]\\d|50677[0-8])", new int[] { 16 }, true, 3));
            add(new Pattern("^(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})", new int[] { 16 }, true, 3));
            add(new Pattern("^65003[1-3]", new int[] { 16 }, true, 3));
            add(new Pattern("^(65003[5-9]|65004\\d|65005[0-1])", new int[] { 16 }, true, 3));
            add(new Pattern("^(65040[5-9]|6504[1-3]\\d)", new int[] { 16 }, true, 3));
            add(new Pattern("^(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])", new int[] { 16 }, true, 3));
            add(new Pattern("^(65054[1-9]|6505[5-8]\\d|65059[0-8])", new int[] { 16 }, true, 3));
            add(new Pattern("^(65070\\d|65071[0-8])", new int[] { 16 }, true, 3));
            add(new Pattern("^6507(2[0-7])", new int[] { 16 }, true, 3));
            add(new Pattern("^6509[0-9]", new int[] { 16 }, true, 3));
            add(new Pattern("^(65165[2-9]|6516[6-7]\\d)", new int[] { 16 }, true, 3));
            add(new Pattern("^(65500\\d|65501\\d)", new int[] { 16 }, true, 3));
            add(new Pattern("^(65502[1-9]|6550[3-4]\\d|65505[0-8])", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins2 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata2 = new HashMap<>();
        metadata2.put("sourceFile", "elo.json");
        add(new BrandDetailed("elo", "Elo", "credit", new int[] { 16 }, true, 3, patterns2, new String[] { "BR" }, metadata2, new String[] { "visa", "aura", "discover", "banesecard" }, bins2));
        List<Pattern> patterns3 = new ArrayList<Pattern>() {{
            add(new Pattern("^(?:2131|1800|35)", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins3 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata3 = new HashMap<>();
        metadata3.put("sourceFile", "jcb.json");
        add(new BrandDetailed("jcb", "JCB", "credit", new int[] { 16 }, true, 3, patterns3, new String[] { "GLOBAL" }, metadata3, new String[0], bins3));
        List<Pattern> patterns4 = new ArrayList<Pattern>() {{
            add(new Pattern("^5[1-5]", new int[] { 16 }, true, 3));
            add(new Pattern("^2[2-7][0-2][0-9]", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins4 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata4 = new HashMap<>();
        metadata4.put("sourceFile", "mastercard.json");
        add(new BrandDetailed("mastercard", "Mastercard", "credit", new int[] { 16 }, true, 3, patterns4, new String[] { "GLOBAL" }, metadata4, new String[0], bins4));
        List<Pattern> patterns5 = new ArrayList<Pattern>() {{
            add(new Pattern("^50", new int[] { 16, 17, 18, 19 }, true, 3));
        }};
        List<Bin> bins5 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata5 = new HashMap<>();
        metadata5.put("sourceFile", "aura.json");
        add(new BrandDetailed("aura", "Aura", "credit", new int[] { 16, 17, 18, 19 }, true, 3, patterns5, new String[] { "BR" }, metadata5, new String[] { "maestro" }, bins5));
        List<Pattern> patterns6 = new ArrayList<Pattern>() {{
            add(new Pattern("^636117", new int[] { 16 }, true, 3));
            add(new Pattern("^637473", new int[] { 16 }, true, 3));
            add(new Pattern("^637470", new int[] { 16 }, true, 3));
            add(new Pattern("^637472", new int[] { 16 }, true, 3));
            add(new Pattern("^650725", new int[] { 16 }, true, 3));
            add(new Pattern("^650046", new int[] { 16 }, true, 3));
            add(new Pattern("^650591", new int[] { 16 }, true, 3));
            add(new Pattern("^651668", new int[] { 16 }, true, 3));
            add(new Pattern("^651679", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins6 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata6 = new HashMap<>();
        metadata6.put("sourceFile", "banesecard.json");
        add(new BrandDetailed("banesecard", "BaneseCard", "credit", new int[] { 16 }, true, 3, patterns6, new String[] { "BR" }, metadata6, new String[] { "discover" }, bins6));
        List<Pattern> patterns7 = new ArrayList<Pattern>() {{
            add(new Pattern("^5018", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^5020", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^5038", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^5893", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^6304", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^6759", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^676[1-3]", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
            add(new Pattern("^6706", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3));
        }};
        List<Bin> bins7 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata7 = new HashMap<>();
        metadata7.put("sourceFile", "maestro.json");
        add(new BrandDetailed("maestro", "Maestro", "debit", new int[] { 12, 13, 14, 15, 16, 17, 18, 19 }, true, 3, patterns7, new String[] { "GLOBAL" }, metadata7, new String[0], bins7));
        List<Pattern> patterns8 = new ArrayList<Pattern>() {{
            add(new Pattern("^4", new int[] { 13, 16 }, true, 3));
            add(new Pattern("^6367", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins8 = new ArrayList<Bin>() {{
            add(new Bin("491441", "CREDIT", null, "BANCO PROSPER, S.A.", new String[] { "BR" }));
            add(new Bin("491440", "CREDIT", null, "BANCO PROSPER, S.A.", new String[] { "BR" }));
            add(new Bin("491439", "CREDIT", null, "BANCO PROSPER, S.A.", new String[] { "BR" }));
            add(new Bin("491423", "CREDIT", null, "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)", new String[] { "BR" }));
            add(new Bin("491416", "CREDIT", "CLASSIC", "BANCO DO ESTADO DO PARANA", new String[] { "BR" }));
            add(new Bin("491415", "CREDIT", "CLASSIC", "BANCO DO ESTADO DO PARANA", new String[] { "BR" }));
            add(new Bin("491414", "CREDIT", "GOLD", "BANCO DO ESTADO DO PARANA", new String[] { "BR" }));
            add(new Bin("491413", "CREDIT", "CLASSIC", "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A", new String[] { "BR" }));
            add(new Bin("491412", "CREDIT", "CLASSIC", "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A", new String[0]));
            add(new Bin("491411", "CREDIT", "GOLD", "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A", new String[0]));
            add(new Bin("491402", "CREDIT", null, "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)", new String[0]));
            add(new Bin("491316", "CREDIT", "CLASSIC", "BANCO SANTANDER BRASIL, S.A.", new String[0]));
            add(new Bin("491315", "CREDIT", "CLASSIC", "BANCO SANTANDER, S.A.", new String[0]));
            add(new Bin("491314", "CREDIT", "GOLD", "BANCO SANTANDER, S.A.", new String[0]));
            add(new Bin("491256", "CREDIT", "PLATINUM", "BANCO PANAMERICANO, S.A.", new String[0]));
        }};
        Map<String, Object> metadata8 = new HashMap<>();
        metadata8.put("sourceFile", new String[] { "visa/base.json", "visa/bins-br-1.json", "visa/bins-br-2.json" });
        add(new BrandDetailed("visa", "Visa", "credit", new int[] { 13, 16 }, true, 3, patterns8, new String[] { "GLOBAL" }, metadata8, new String[0], bins8));
        List<Pattern> patterns9 = new ArrayList<Pattern>() {{
            add(new Pattern("^6011", new int[] { 16, 19 }, true, 3));
            add(new Pattern("^64[4-9]", new int[] { 16, 19 }, true, 3));
            add(new Pattern("^65", new int[] { 16, 19 }, true, 3));
        }};
        List<Bin> bins9 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata9 = new HashMap<>();
        metadata9.put("sourceFile", "discover.json");
        add(new BrandDetailed("discover", "Discover", "credit", new int[] { 16, 19 }, true, 3, patterns9, new String[] { "US" }, metadata9, new String[] { "hipercard", "unionpay" }, bins9));
        List<Pattern> patterns10 = new ArrayList<Pattern>() {{
            add(new Pattern("^38", new int[] { 19 }, true, 3));
            add(new Pattern("^60", new int[] { 16 }, true, 3));
        }};
        List<Bin> bins10 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata10 = new HashMap<>();
        metadata10.put("sourceFile", "hipercard.json");
        add(new BrandDetailed("hipercard", "Hipercard", "credit", new int[] { 16, 19 }, true, 3, patterns10, new String[] { "BR" }, metadata10, new String[0], bins10));
        List<Pattern> patterns11 = new ArrayList<Pattern>() {{
            add(new Pattern("^62", new int[] { 16, 17, 18, 19 }, true, 3));
        }};
        List<Bin> bins11 = new ArrayList<Bin>() {{
        }};
        Map<String, Object> metadata11 = new HashMap<>();
        metadata11.put("sourceFile", "unionpay.json");
        add(new BrandDetailed("unionpay", "UnionPay", "debit", new int[] { 16, 17, 18, 19 }, true, 3, patterns11, new String[] { "CN", "GLOBAL" }, metadata11, new String[0], bins11));
    }};
}
