// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-15T00:50:32.575Z

package br.com.s2n.creditcard.identifier;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * Credit card brand data (detailed).
 * Loads bins from JSON at runtime to handle large data efficiently.
 */
public class BrandDataDetailed {

    public static class Pattern {
        public String bin;
        public int[] length;
        public boolean luhn;
        public int cvvLength;
    }

    public static class Bin {
        public String bin;
        public String type;
        public String category;
        public String issuer;
        public String[] countries;
    }

    public static class Number {
        public int[] lengths;
        public boolean luhn;
    }

    public static class Cvv {
        public int length;
    }

    public static class BrandDetailed {
        public String scheme;
        public String brand;
        public String type;
        public Number number;
        public Cvv cvv;
        public List<Pattern> patterns;
        public String[] countries;
        public Map<String, Object> metadata;
        public String[] priorityOver;
        public List<Bin> bins;
    }

    private static List<BrandDetailed> brandsCache = null;

    /**
     * Get all detailed brand data (lazy-loaded from JSON).
     */
    public static synchronized List<BrandDetailed> getBrands() {
        if (brandsCache == null) {
            brandsCache = loadBrandsFromJson();
        }
        return brandsCache;
    }

    private static List<BrandDetailed> loadBrandsFromJson() {
        try (InputStream is = BrandDataDetailed.class.getResourceAsStream("/cards-detailed.json");
             InputStreamReader reader = new InputStreamReader(is, StandardCharsets.UTF_8)) {
            Gson gson = new Gson();
            Type listType = new TypeToken<List<BrandDetailed>>(){}.getType();
            return gson.fromJson(reader, listType);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load cards-detailed.json", e);
        }
    }
}
