'use strict';

/**
 * C# code generators
 */

const { LANG_CONFIG, toNativeValue, extractSimplifiedBrand, extractDetailedBrand } = require('./utils');

const cs = LANG_CONFIG.csharp;

/**
 * Generate C# native data file (simplified)
 */
function generateCSharp(brands) {
  const lines = [
    '// Auto-generated by bin-cc build - DO NOT EDIT',
    `// Generated: ${new Date().toISOString()}`,
    '',
    'using System;',
    'using System.Text.RegularExpressions;',
    '',
    'namespace CreditCardIdentifier',
    '{',
    '    /// <summary>',
    '    /// Credit card brand data.',
    '    /// </summary>',
    '    public static class BrandData',
    '    {',
    '        /// <summary>',
    '        /// Brand definition.',
    '        /// </summary>',
    '        public class Brand',
    '        {',
    '            public string Name { get; set; }',
    '            public string[] PriorityOver { get; set; }',
    '            public Regex RegexpBin { get; set; }',
    '            public Regex RegexpFull { get; set; }',
    '            public Regex RegexpCvv { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// All supported credit card brands.',
    '        /// </summary>',
    '        public static readonly Brand[] Brands = new Brand[]',
    '        {'
  ];

  for (const brand of brands) {
    const b = extractSimplifiedBrand(brand);
    lines.push('            new Brand');
    lines.push('            {');
    lines.push(`                Name = ${cs.string(b.name)},`);
    lines.push(`                PriorityOver = ${cs.stringArray(b.priorityOver.map(s => cs.string(s)))},`);
    lines.push(`                RegexpBin = new Regex(${cs.verbatimString(b.regexpBin)}, RegexOptions.Compiled),`);
    lines.push(`                RegexpFull = new Regex(${cs.verbatimString(b.regexpFull)}, RegexOptions.Compiled),`);
    lines.push(`                RegexpCvv = new Regex(${cs.verbatimString(b.regexpCvv)}, RegexOptions.Compiled),`);
    lines.push('            },');
  }

  lines.push('        };');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate C# native data file (detailed)
 */
function generateCSharpDetailed(detailed) {
  const lines = [
    '// Auto-generated by bin-cc build - DO NOT EDIT',
    `// Generated: ${new Date().toISOString()}`,
    '',
    'using System;',
    'using System.Collections.Generic;',
    '',
    'namespace CreditCardIdentifier',
    '{',
    '    /// <summary>',
    '    /// Credit card brand data (detailed).',
    '    /// </summary>',
    '    public static class BrandDataDetailed',
    '    {',
    '        /// <summary>',
    '        /// Number validation info',
    '        /// </summary>',
    '        public class NumberInfo',
    '        {',
    '            public int[] Lengths { get; set; }',
    '            public bool Luhn { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// CVV validation info',
    '        /// </summary>',
    '        public class CvvInfo',
    '        {',
    '            public int Length { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// Pattern info',
    '        /// </summary>',
    '        public class Pattern',
    '        {',
    '            public string Bin { get; set; }',
    '            public int[] Length { get; set; }',
    '            public bool Luhn { get; set; }',
    '            public int CvvLength { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// BIN info',
    '        /// </summary>',
    '        public class BinInfo',
    '        {',
    '            public string Bin { get; set; }',
    '            public string Type { get; set; }',
    '            public string Category { get; set; }',
    '            public string Issuer { get; set; }',
    '            public string[] Countries { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// Detailed brand info',
    '        /// </summary>',
    '        public class Brand',
    '        {',
    '            public string Scheme { get; set; }',
    '            public string BrandName { get; set; }',
    '            public string Type { get; set; }',
    '            public NumberInfo Number { get; set; }',
    '            public CvvInfo Cvv { get; set; }',
    '            public Pattern[] Patterns { get; set; }',
    '            public string[] Countries { get; set; }',
    '            public Dictionary<string, object> Metadata { get; set; }',
    '            public string[] PriorityOver { get; set; }',
    '            public BinInfo[] Bins { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// All detailed brand data',
    '        /// </summary>',
    '        public static readonly Brand[] Brands = new Brand[]',
    '        {'
  ];

  for (const brand of detailed) {
    const b = extractDetailedBrand(brand);
    lines.push('            new Brand');
    lines.push('            {');
    lines.push(`                Scheme = ${cs.string(b.scheme)},`);
    lines.push(`                BrandName = ${cs.string(b.brand)},`);
    lines.push(`                Type = ${cs.string(b.type)},`);
    lines.push('                Number = new NumberInfo');
    lines.push('                {');
    lines.push(`                    Lengths = ${cs.intArray(b.number.lengths)},`);
    lines.push(`                    Luhn = ${toNativeValue(b.number.luhn, 'csharp')}`);
    lines.push('                },');
    lines.push('                Cvv = new CvvInfo');
    lines.push('                {');
    lines.push(`                    Length = ${b.cvv.length}`);
    lines.push('                },');
    lines.push('                Patterns = new Pattern[]');
    lines.push('                {');
    for (const pattern of b.patterns) {
      lines.push('                    new Pattern');
      lines.push('                    {');
      lines.push(`                        Bin = ${cs.string(pattern.bin)},`);
      lines.push(`                        Length = ${cs.intArray(pattern.length)},`);
      lines.push(`                        Luhn = ${toNativeValue(pattern.luhn, 'csharp')},`);
      lines.push(`                        CvvLength = ${pattern.cvvLength}`);
      lines.push('                    },');
    }
    lines.push('                },');
    lines.push(`                Countries = ${cs.stringArray(b.countries.map(c => cs.string(c)))},`);
    
    // Metadata - convert values to native C# values
    const metadataEntries = Object.entries(b.metadata)
      .map(([k, v]) => `{ ${cs.string(k)}, ${toNativeValue(v, 'csharp')} }`)
      .join(', ');
    lines.push(`                Metadata = new Dictionary<string, object> { ${metadataEntries} },`);
    
    // Priority over
    lines.push(`                PriorityOver = ${cs.stringArray(b.priorityOver.map(p => cs.string(p)))},`);
    
    // Bins
    if (b.bins.length > 0) {
      lines.push('                Bins = new BinInfo[]');
      lines.push('                {');
      for (const bin of b.bins) {
        lines.push('                    new BinInfo');
        lines.push('                    {');
        lines.push(`                        Bin = ${cs.string(bin.bin)},`);
        lines.push(`                        Type = ${cs.string(bin.type || '')},`);
        lines.push(`                        Category = ${cs.string(bin.category || '')},`);
        lines.push(`                        Issuer = ${cs.string(bin.issuer || '')},`);
        lines.push(`                        Countries = ${cs.stringArray((bin.countries || []).map(c => cs.string(c)))}`);
        lines.push('                    },');
      }
      lines.push('                }');
    } else {
      lines.push('                Bins = Array.Empty<BinInfo>()');
    }
    
    lines.push('            },');
  }

  lines.push('        };');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

module.exports = {
  generateCSharp,
  generateCSharpDetailed,
};
