'use strict';

/**
 * Elixir code generators
 */

const { LANG_CONFIG, toNativeValue, extractSimplifiedBrand, extractDetailedBrand } = require('./utils');

const ex = LANG_CONFIG.elixir;

/**
 * Generate Elixir native data file (simplified)
 */
function generateElixir(brands) {
  const lines = [
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'defmodule CreditcardIdentifier.Data do',
    '  @moduledoc """',
    '  Credit card brand data.',
    '  """',
    '',
    '  @doc """',
    '  Returns all credit card brands.',
    '  """',
    '  @spec brands() :: [map()]',
    '  def brands do',
    '    ['
  ];

  for (const brand of brands) {
    const b = extractSimplifiedBrand(brand);
    lines.push('      %{');
    lines.push(`        name: ${ex.string(b.name)},`);
    lines.push(`        priority_over: ${toNativeValue(b.priorityOver, 'elixir')},`);
    lines.push(`        regexp_bin: ${ex.regex(b.regexpBin)},`);
    lines.push(`        regexp_full: ${ex.regex(b.regexpFull)},`);
    lines.push(`        regexp_cvv: ${ex.regex(b.regexpCvv)}`);
    lines.push('      },');
  }

  lines.push('    ]');
  lines.push('  end');
  lines.push('end');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate Elixir native data file (detailed)
 * Loads bins from JSON at runtime to avoid huge source files
 */
function generateElixirDetailed(detailed) {
  const lines = [
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'defmodule CreditcardIdentifier.DataDetailed do',
    '  @moduledoc """',
    '  Credit card brand data (detailed).',
    '  Loads bins from JSON at runtime to handle large data efficiently.',
    '  """',
    '',
    '  @json_path Path.join(:code.priv_dir(:creditcard_identifier), "cards-detailed.json")',
    '',
    '  @doc """',
    '  Returns all credit card brands (detailed).',
    '  Data is lazy-loaded from JSON file.',
    '  """',
    '  @spec brands() :: [map()]',
    '  def brands do',
    '    case :persistent_term.get(__MODULE__, nil) do',
    '      nil ->',
    '        data = load_from_json()',
    '        :persistent_term.put(__MODULE__, data)',
    '        data',
    '      data ->',
    '        data',
    '    end',
    '  end',
    '',
    '  defp load_from_json do',
    '    @json_path',
    '    |> File.read!()',
    '    |> Jason.decode!(keys: :atoms)',
    '  end',
    'end',
    '',
  ];

  return lines.join('\n');
}

module.exports = {
  generateElixir,
  generateElixirDetailed,
};
