'use strict';

/**
 * JavaScript/TypeScript code generators
 */

const { extractSimplifiedBrand, fileHeader } = require('./utils');

/**
 * Generate JavaScript native data file (simplified)
 */
function generateJavaScript(brands) {
  const lines = [
    ...fileHeader('//'),
    "'use strict';",
    '',
    '/**',
    ' * Credit card brand data (simplified)',
    ' * @type {Array<{name: string, priorityOver: string[], regexpBin: string, regexpFull: string, regexpCvv: string}>}',
    ' */',
    'const brands = ['
  ];

  for (const brand of brands) {
    const b = extractSimplifiedBrand(brand);
    lines.push('  {');
    lines.push(`    name: ${JSON.stringify(b.name)},`);
    lines.push(`    priorityOver: ${JSON.stringify(b.priorityOver)},`);
    lines.push(`    regexpBin: ${JSON.stringify(b.regexpBin)},`);
    lines.push(`    regexpFull: ${JSON.stringify(b.regexpFull)},`);
    lines.push(`    regexpCvv: ${JSON.stringify(b.regexpCvv)},`);
    lines.push('  },');
  }

  lines.push('];', '', 'module.exports = brands;', '');
  return lines.join('\n');
}

/**
 * Generate JavaScript native data file (detailed)
 */
function generateJavaScriptDetailed(detailed) {
  const lines = [
    ...fileHeader('//'),
    "'use strict';",
    '',
    '/**',
    ' * Credit card brand data (detailed)',
    ' */',
    'const brandsDetailed = ' + JSON.stringify(detailed, null, 2) + ';',
    '',
    'module.exports = brandsDetailed;',
    ''
  ];
  return lines.join('\n');
}

/**
 * Generate TypeScript declaration file (simplified)
 */
function generateTypeScriptDeclaration() {
  return `// Auto-generated by bin-cc build - DO NOT EDIT

export interface Brand {
  name: string;
  priorityOver: string[];
  regexpBin: string;
  regexpFull: string;
  regexpCvv: string;
}

declare const brands: Brand[];
export = brands;
`;
}

/**
 * Generate TypeScript declaration file (detailed)
 */
function generateTypeScriptDeclarationDetailed() {
  return `// Auto-generated by bin-cc build - DO NOT EDIT

export interface Pattern {
  bin: string;
  length: number[];
  luhn: boolean;
  cvvLength: number;
}

export interface BrandDetailed {
  scheme: string;
  brand: string;
  type: string;
  priorityOver: string[];
  number: {
    lengths: number[];
    luhn: boolean;
  };
  cvv: {
    length: number;
  };
  patterns: Pattern[];
  countries: string[];
  unofficial?: boolean;
  metadata: {
    sourceFile: string;
  };
}

declare const brandsDetailed: BrandDetailed[];
export = brandsDetailed;
`;
}

module.exports = {
  generateJavaScript,
  generateJavaScriptDetailed,
  generateTypeScriptDeclaration,
  generateTypeScriptDeclarationDetailed,
};
