'use strict';

/**
 * Ruby code generators
 */

const { LANG_CONFIG, toNativeValue, extractSimplifiedBrand, extractDetailedBrand } = require('./utils');

const rb = LANG_CONFIG.ruby;

/**
 * Generate Ruby native data file (simplified)
 */
function generateRuby(brands) {
  const lines = [
    '# frozen_string_literal: true',
    '',
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'module CreditcardIdentifier',
    '  # Credit card brand data',
    '  BRANDS = ['
  ];

  for (const brand of brands) {
    const b = extractSimplifiedBrand(brand);
    lines.push('    {');
    lines.push(`      name: ${rb.string(b.name)},`);
    lines.push(`      priority_over: ${toNativeValue(b.priorityOver, 'ruby')},`);
    lines.push(`      regexp_bin: ${rb.regex(b.regexpBin)},`);
    lines.push(`      regexp_full: ${rb.regex(b.regexpFull)},`);
    lines.push(`      regexp_cvv: ${rb.regex(b.regexpCvv)},`);
    lines.push('    },');
  }

  lines.push('  ].freeze', 'end', '');
  return lines.join('\n');
}

/**
 * Generate Ruby native data file (detailed)
 * Loads bins from JSON at runtime to avoid huge source files
 */
function generateRubyDetailed(detailed) {
  const lines = [
    '# frozen_string_literal: true',
    '',
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'require \'json\'',
    '',
    'module CreditcardIdentifier',
    '  # Credit card brand data (detailed)',
    '  # Loads bins from JSON at runtime to handle large data efficiently.',
    '',
    '  class << self',
    '    def brands_detailed',
    '      @brands_detailed ||= load_brands_from_json',
    '    end',
    '',
    '    private',
    '',
    '    def load_brands_from_json',
    '      json_path = File.join(__dir__, \'cards-detailed.json\')',
    '      JSON.parse(File.read(json_path), symbolize_names: true)',
    '    end',
    '  end',
    '',
    '  # Deprecated: Use CreditcardIdentifier.brands_detailed instead',
    '  BRANDS_DETAILED = [].freeze',
    'end',
    '',
  ];

  return lines.join('\n');
}

module.exports = {
  generateRuby,
  generateRubyDetailed,
};
