'use strict';

/**
 * Ruby code generators
 */

const { LANG_CONFIG, toNativeValue, extractSimplifiedBrand, extractDetailedBrand } = require('./utils');

const rb = LANG_CONFIG.ruby;

/**
 * Generate Ruby native data file (simplified)
 */
function generateRuby(brands) {
  const lines = [
    '# frozen_string_literal: true',
    '',
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'module CreditcardIdentifier',
    '  # Credit card brand data',
    '  BRANDS = ['
  ];

  for (const brand of brands) {
    const b = extractSimplifiedBrand(brand);
    lines.push('    {');
    lines.push(`      name: ${rb.string(b.name)},`);
    lines.push(`      priority_over: ${toNativeValue(b.priorityOver, 'ruby')},`);
    lines.push(`      regexp_bin: ${rb.regex(b.regexpBin)},`);
    lines.push(`      regexp_full: ${rb.regex(b.regexpFull)},`);
    lines.push(`      regexp_cvv: ${rb.regex(b.regexpCvv)},`);
    lines.push('    },');
  }

  lines.push('  ].freeze', 'end', '');
  return lines.join('\n');
}

/**
 * Generate Ruby native data file (detailed)
 */
function generateRubyDetailed(detailed) {
  const lines = [
    '# frozen_string_literal: true',
    '',
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'module CreditcardIdentifier',
    '  # Credit card brand data (detailed)',
    '  BRANDS_DETAILED = ['
  ];

  for (const brand of detailed) {
    const b = extractDetailedBrand(brand);
    lines.push('    {');
    lines.push(`      scheme: ${toNativeValue(b.scheme, 'ruby')},`);
    lines.push(`      brand: ${toNativeValue(b.brand, 'ruby')},`);
    lines.push(`      type: ${toNativeValue(b.type, 'ruby')},`);
    lines.push('      number: {');
    lines.push(`        lengths: ${toNativeValue(b.number.lengths, 'ruby')},`);
    lines.push(`        luhn: ${toNativeValue(b.number.luhn, 'ruby')}`);
    lines.push('      },');
    lines.push('      cvv: {');
    lines.push(`        length: ${b.cvv.length}`);
    lines.push('      },');
    lines.push('      patterns: [');
    for (const pattern of b.patterns) {
      lines.push('        {');
      lines.push(`          bin: ${toNativeValue(pattern.bin, 'ruby')},`);
      lines.push(`          length: ${toNativeValue(pattern.length, 'ruby')},`);
      lines.push(`          luhn: ${toNativeValue(pattern.luhn, 'ruby')},`);
      lines.push(`          cvv_length: ${pattern.cvvLength}`);
      lines.push('        },');
    }
    lines.push('      ],');
    lines.push(`      countries: ${toNativeValue(b.countries, 'ruby')},`);
    lines.push(`      metadata: ${toNativeValue(b.metadata, 'ruby')},`);
    lines.push(`      priority_over: ${toNativeValue(b.priorityOver, 'ruby')},`);
    
    if (b.bins.length > 0) {
      lines.push('      bins: [');
      for (const bin of b.bins) {
        lines.push('        {');
        lines.push(`          bin: ${toNativeValue(bin.bin, 'ruby')},`);
        lines.push(`          type: ${toNativeValue(bin.type, 'ruby')},`);
        lines.push(`          category: ${toNativeValue(bin.category, 'ruby')},`);
        lines.push(`          issuer: ${toNativeValue(bin.issuer, 'ruby')},`);
        lines.push(`          countries: ${toNativeValue(bin.countries || [], 'ruby')}`);
        lines.push('        },');
      }
      lines.push('      ]');
    } else {
      lines.push('      bins: []');
    }
    
    lines.push('    },');
  }

  lines.push('  ].freeze', 'end', '');
  return lines.join('\n');
}

module.exports = {
  generateRuby,
  generateRubyDetailed,
};
