# frozen_string_literal: true

# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-12T10:19:57.958Z

module CreditcardIdentifier
  # Credit card brand data (detailed)
  BRANDS_DETAILED = [
    {
      scheme: "amex",
      brand: "American Express",
      type: "credit",
      number: {
        lengths: [15],
        luhn: true
      },
      cvv: {
        length: 4
      },
      patterns: [
        {
          bin: "^3[47]",
          length: [15],
          luhn: true,
          cvv_length: 4
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => "amex.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "diners",
      brand: "Diners Club",
      type: "credit",
      number: {
        lengths: [14],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^3(?:0[0-5]|[68][0-9])",
          length: [14],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => "diners.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "elo",
      brand: "Elo",
      type: "credit",
      number: {
        lengths: [16],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^401178|^401179|^431274|^438935|^451416|^457393|^457631|^457632|^504175",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^627780|^636297|^636368",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(506699|5067[0-6]\\d|50677[0-8])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^65003[1-3]",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65003[5-9]|65004\\d|65005[0-1])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65040[5-9]|6504[1-3]\\d)",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65054[1-9]|6505[5-8]\\d|65059[0-8])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65070\\d|65071[0-8])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6507(2[0-7])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6509[0-9]",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65165[2-9]|6516[6-7]\\d)",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65500\\d|65501\\d)",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^(65502[1-9]|6550[3-4]\\d|65505[0-8])",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["BR"],
      metadata: { "sourceFile" => "elo.json" },
      priority_over: ["visa", "aura", "discover", "banesecard"],
      bins: []
    },
    {
      scheme: "jcb",
      brand: "JCB",
      type: "credit",
      number: {
        lengths: [16],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^(?:2131|1800|35)",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => "jcb.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "mastercard",
      brand: "Mastercard",
      type: "credit",
      number: {
        lengths: [16],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^5[1-5]",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^2[2-7][0-2][0-9]",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => "mastercard.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "aura",
      brand: "Aura",
      type: "credit",
      number: {
        lengths: [16, 17, 18, 19],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^50",
          length: [16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["BR"],
      metadata: { "sourceFile" => "aura.json" },
      priority_over: ["maestro"],
      bins: []
    },
    {
      scheme: "banesecard",
      brand: "BaneseCard",
      type: "credit",
      number: {
        lengths: [16],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^636117",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^637473",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^637470",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^637472",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^650725",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^650046",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^650591",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^651668",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^651679",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["BR"],
      metadata: { "sourceFile" => "banesecard.json" },
      priority_over: ["discover"],
      bins: []
    },
    {
      scheme: "maestro",
      brand: "Maestro",
      type: "debit",
      number: {
        lengths: [12, 13, 14, 15, 16, 17, 18, 19],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^5018",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^5020",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^5038",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^5893",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6304",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6759",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^676[1-3]",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6706",
          length: [12, 13, 14, 15, 16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => "maestro.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "visa",
      brand: "Visa",
      type: "credit",
      number: {
        lengths: [13, 16],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^4",
          length: [13, 16],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^6367",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["GLOBAL"],
      metadata: { "sourceFile" => ["visa/base.json", "visa/bins-br-1.json", "visa/bins-br-2.json"] },
      priority_over: [],
      bins: [
        {
          bin: "491441",
          type: "CREDIT",
          category: nil,
          issuer: "BANCO PROSPER, S.A.",
          countries: ["BR"]
        },
        {
          bin: "491440",
          type: "CREDIT",
          category: nil,
          issuer: "BANCO PROSPER, S.A.",
          countries: ["BR"]
        },
        {
          bin: "491439",
          type: "CREDIT",
          category: nil,
          issuer: "BANCO PROSPER, S.A.",
          countries: ["BR"]
        },
        {
          bin: "491423",
          type: "CREDIT",
          category: nil,
          issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
          countries: ["BR"]
        },
        {
          bin: "491416",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO DO ESTADO DO PARANA",
          countries: ["BR"]
        },
        {
          bin: "491415",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO DO ESTADO DO PARANA",
          countries: ["BR"]
        },
        {
          bin: "491414",
          type: "CREDIT",
          category: "GOLD",
          issuer: "BANCO DO ESTADO DO PARANA",
          countries: ["BR"]
        },
        {
          bin: "491413",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
          countries: ["BR"]
        },
        {
          bin: "491412",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
          countries: []
        },
        {
          bin: "491411",
          type: "CREDIT",
          category: "GOLD",
          issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
          countries: []
        },
        {
          bin: "491402",
          type: "CREDIT",
          category: nil,
          issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
          countries: []
        },
        {
          bin: "491316",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO SANTANDER BRASIL, S.A.",
          countries: []
        },
        {
          bin: "491315",
          type: "CREDIT",
          category: "CLASSIC",
          issuer: "BANCO SANTANDER, S.A.",
          countries: []
        },
        {
          bin: "491314",
          type: "CREDIT",
          category: "GOLD",
          issuer: "BANCO SANTANDER, S.A.",
          countries: []
        },
        {
          bin: "491256",
          type: "CREDIT",
          category: "PLATINUM",
          issuer: "BANCO PANAMERICANO, S.A.",
          countries: []
        },
      ]
    },
    {
      scheme: "discover",
      brand: "Discover",
      type: "credit",
      number: {
        lengths: [16, 19],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^6011",
          length: [16, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^64[4-9]",
          length: [16, 19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^65",
          length: [16, 19],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["US"],
      metadata: { "sourceFile" => "discover.json" },
      priority_over: ["hipercard", "unionpay"],
      bins: []
    },
    {
      scheme: "hipercard",
      brand: "Hipercard",
      type: "credit",
      number: {
        lengths: [16, 19],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^38",
          length: [19],
          luhn: true,
          cvv_length: 3
        },
        {
          bin: "^60",
          length: [16],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["BR"],
      metadata: { "sourceFile" => "hipercard.json" },
      priority_over: [],
      bins: []
    },
    {
      scheme: "unionpay",
      brand: "UnionPay",
      type: "debit",
      number: {
        lengths: [16, 17, 18, 19],
        luhn: true
      },
      cvv: {
        length: 3
      },
      patterns: [
        {
          bin: "^62",
          length: [16, 17, 18, 19],
          luhn: true,
          cvv_length: 3
        },
      ],
      countries: ["CN", "GLOBAL"],
      metadata: { "sourceFile" => "unionpay.json" },
      priority_over: [],
      bins: []
    },
  ].freeze
end
