# frozen_string_literal: true

# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-15T00:50:32.434Z

require 'json'

module CreditcardIdentifier
  # Credit card brand data (detailed)
  # Loads bins from JSON at runtime to handle large data efficiently.

  class << self
    def brands_detailed
      @brands_detailed ||= load_brands_from_json
    end

    private

    def load_brands_from_json
      json_path = File.join(__dir__, 'cards-detailed.json')
      JSON.parse(File.read(json_path), symbolize_names: true)
    end
  end

  # Deprecated: Use CreditcardIdentifier.brands_detailed instead
  BRANDS_DETAILED = [].freeze
end
