# frozen_string_literal: true

# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-12T09:59:23.119Z

module CreditcardIdentifier
  # Credit card brand data
  BRANDS = [
    {
      name: "amex",
      priority_over: [],
      regexp_bin: /\A(3[47])/,
      regexp_full: /\A(?=.{15}$)(?:3[47])[0-9]*\z/,
      regexp_cvv: /\A\d{4}\z/,
    },
    {
      name: "diners",
      priority_over: [],
      regexp_bin: /\A(3(?:0[0-5]|[68][0-9]))/,
      regexp_full: /\A(?=.{14}$)(?:3(?:0[0-5]|[68][0-9]))[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "elo",
      priority_over: ["visa", "aura", "discover", "banesecard"],
      regexp_bin: /\A(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))/,
      regexp_full: /\A(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "jcb",
      priority_over: [],
      regexp_bin: /\A((?:2131|1800|35))/,
      regexp_full: /\A(?=.{16}$)(?:(?:2131|1800|35))[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "mastercard",
      priority_over: [],
      regexp_bin: /\A(5[1-5]|2[2-7][0-2][0-9])/,
      regexp_full: /\A(?=.{16}$)(?:5[1-5]|2[2-7][0-2][0-9])[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "aura",
      priority_over: ["maestro"],
      regexp_bin: /\A(50)/,
      regexp_full: /\A(?=.{16,19}$)(?:50)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "banesecard",
      priority_over: ["discover"],
      regexp_bin: /\A(636117|637473|637470|637472|650725|650046|650591|651668|651679)/,
      regexp_full: /\A(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "maestro",
      priority_over: [],
      regexp_bin: /\A(5018|5020|5038|5893|6304|6759|676[1-3]|6706)/,
      regexp_full: /\A(?=.{12,19}$)(?:5018|5020|5038|5893|6304|6759|676[1-3]|6706)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "visa",
      priority_over: [],
      regexp_bin: /\A(4|6367)/,
      regexp_full: /\A(?=.{13,16}$)(?:4|6367)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "discover",
      priority_over: ["hipercard", "unionpay"],
      regexp_bin: /\A(6011|64[4-9]|65)/,
      regexp_full: /\A(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "hipercard",
      priority_over: [],
      regexp_bin: /\A(38|60)/,
      regexp_full: /\A(?=.{16,19}$)(?:38|60)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
    {
      name: "unionpay",
      priority_over: [],
      regexp_bin: /\A(62)/,
      regexp_full: /\A(?=.{16,19}$)(?:62)[0-9]*\z/,
      regexp_cvv: /\A\d{3}\z/,
    },
  ].freeze
end
