// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-15T00:50:32.529Z

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text.Json;

namespace CreditCardIdentifier
{
    /// <summary>
    /// Credit card brand data (detailed).
    /// Loads bins from JSON at runtime to handle large data efficiently.
    /// </summary>
    public static class BrandDataDetailed
    {
        public class NumberInfo
        {
            public int[] Lengths { get; set; }
            public bool Luhn { get; set; }
        }

        public class CvvInfo
        {
            public int Length { get; set; }
        }

        public class Pattern
        {
            public string Bin { get; set; }
            public int[] Length { get; set; }
            public bool Luhn { get; set; }
            public int CvvLength { get; set; }
        }

        public class BinInfo
        {
            public string Bin { get; set; }
            public string Type { get; set; }
            public string Category { get; set; }
            public string Issuer { get; set; }
            public string[] Countries { get; set; }
        }

        public class Brand
        {
            public string Scheme { get; set; }
            public string BrandName { get; set; }
            public string Type { get; set; }
            public NumberInfo Number { get; set; }
            public CvvInfo Cvv { get; set; }
            public Pattern[] Patterns { get; set; }
            public string[] Countries { get; set; }
            public Dictionary<string, object> Metadata { get; set; }
            public string[] PriorityOver { get; set; }
            public BinInfo[] Bins { get; set; }
        }

        private static Brand[] _brandsCache;
        private static readonly object _lock = new object();

        /// <summary>
        /// Get all detailed brand data (lazy-loaded from JSON).
        /// </summary>
        public static Brand[] Brands
        {
            get
            {
                if (_brandsCache == null)
                {
                    lock (_lock)
                    {
                        if (_brandsCache == null)
                        {
                            _brandsCache = LoadBrandsFromJson();
                        }
                    }
                }
                return _brandsCache;
            }
        }

        private static Brand[] LoadBrandsFromJson()
        {
            var assembly = Assembly.GetExecutingAssembly();
            using var stream = assembly.GetManifestResourceStream("CreditCardIdentifier.cards-detailed.json");
            if (stream == null)
            {
                throw new InvalidOperationException("Could not find embedded resource cards-detailed.json");
            }
            using var reader = new StreamReader(stream);
            var json = reader.ReadToEnd();
            return JsonSerializer.Deserialize<Brand[]>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });
        }
    }
}
