// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-14T23:52:35.476Z

using System;
using System.Text.RegularExpressions;

namespace CreditCardIdentifier
{
    /// <summary>
    /// Credit card brand data.
    /// </summary>
    public static class BrandData
    {
        /// <summary>
        /// Brand definition.
        /// </summary>
        public class Brand
        {
            public string Name { get; set; }
            public string[] PriorityOver { get; set; }
            public Regex RegexpBin { get; set; }
            public Regex RegexpFull { get; set; }
            public Regex RegexpCvv { get; set; }
        }

        /// <summary>
        /// All supported credit card brands.
        /// </summary>
        public static readonly Brand[] Brands = new Brand[]
        {
            new Brand
            {
                Name = "amex",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(3[47])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{15}$)(?:3[47])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{4}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "bankcard",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(5610|56022[1-5])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:5610|56022[1-5])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "cabal",
                PriorityOver = new string[] { "maestro" },
                RegexpBin = new Regex(@"^(604400|627170|603522|589657|(60420[1-9]|6042[1][0-9])|(6043[0-9]{2}))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:604400|627170|603522|589657|(60420[1-9]|6042[1][0-9])|(6043[0-9]{2}))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "china-t-union",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(31)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{19}$)(?:31)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "dankort",
                PriorityOver = new string[] { "visa" },
                RegexpBin = new Regex(@"^(5019|4571)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:5019|4571)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "diners-enroute",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(2014|2149)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{15}$)(?:2014|2149)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "elo",
                PriorityOver = new string[] { "visa", "aura", "discover", "banesecard" },
                RegexpBin = new Regex(@"^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "humo",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(9860)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:9860)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "lankapay",
                PriorityOver = new string[] { "jcb" },
                RegexpBin = new Regex(@"^(357111)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:357111)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "laser",
                PriorityOver = new string[] { "maestro" },
                RegexpBin = new Regex(@"^(6304|6706|6771|6709)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:6304|6706|6771|6709)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "mastercard",
                PriorityOver = new string[] { "diners-us-canada", "mir", "borica" },
                RegexpBin = new Regex(@"^(5[1-5]|2(?:2(?:2[1-9]|[3-9][0-9])|[3-6][0-9]{2}|7(?:[0-1][0-9]|20)))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:5[1-5]|2(?:2(?:2[1-9]|[3-9][0-9])|[3-6][0-9]{2}|7(?:[0-1][0-9]|20)))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "napas",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(9704)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:9704)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "naranja",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(589562)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:589562)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "nps-pridnestrovie",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(605474[0-4])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:605474[0-4])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "solo",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(6334|6767)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:6334|6767)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "switch",
                PriorityOver = new string[] { "visa", "maestro" },
                RegexpBin = new Regex(@"^(4903|4905|4911|4936|564182|633110|6333|6759)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:4903|4905|4911|4936|564182|633110|6333|6759)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "uatp",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(1)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{15}$)(?:1)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "ukrcart",
                PriorityOver = new string[] { "hipercard" },
                RegexpBin = new Regex(@"^((60400[1-9][0-9]{2}|6040[1-9][0-9]{3}|604[1][0-9]{4}|6042[0][0][0-9]{2}))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:(60400[1-9][0-9]{2}|6040[1-9][0-9]{3}|604[1][0-9]{4}|6042[0][0][0-9]{2}))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "uzcard",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(8600|5614)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:8600|5614)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "visa-electron",
                PriorityOver = new string[] { "visa" },
                RegexpBin = new Regex(@"^(4026|4405|4508|4844|4913|4917|417500)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:4026|4405|4508|4844|4913|4917|417500)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "banesecard",
                PriorityOver = new string[] { "discover" },
                RegexpBin = new Regex(@"^(636117|637473|637470|637472|650725|650046|650591|651668|651679)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "borica",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(2205)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:2205)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "diners",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(3(?:0[0-5]|6|8|9))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{14}$)(?:3(?:0[0-5]|6|8|9))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "instapayment",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(63[7-9])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:63[7-9])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "interpayment",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(636)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:636)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "jcb",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^((?:2131|1800|35))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "mir",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(220[0-4])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:220[0-4])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "troy",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(65|9792)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:65|9792)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "aura",
                PriorityOver = new string[] { "maestro", "maestro-uk", "gpn", "verve" },
                RegexpBin = new Regex(@"^(50)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:50)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "maestro-uk",
                PriorityOver = new string[] { "maestro" },
                RegexpBin = new Regex(@"^(6759|676770|676774)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{12,19}$)(?:6759|676770|676774)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "discover",
                PriorityOver = new string[] { "hipercard", "unionpay", "gpn", "rupay", "troy", "verve" },
                RegexpBin = new Regex(@"^(6011|64[4-9]|65)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "unionpay",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(62)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:62)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "hipercard",
                PriorityOver = new string[] { "gpn", "diners", "diners-international", "rupay" },
                RegexpBin = new Regex(@"^(384|60)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:384|60)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "rupay",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(60|65|8[12]|508|35[36])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:60|65|8[12]|508|35[36])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "verve",
                PriorityOver = new string[] { "discover", "aura" },
                RegexpBin = new Regex(@"^((5060[9][9]|506[1][0-9]{2}|5061[0-9][0-8])|(65000[2-9]|6500[1][0-9]|6500[2][0-7])|(5078[6-9][5-9]|507[89][0-5][0-9]|5079[0-5][0-9]|50796[0-4]))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:(5060[9][9]|506[1][0-9]{2}|5061[0-9][0-8])|(65000[2-9]|6500[1][0-9]|6500[2][0-7])|(5078[6-9][5-9]|507[89][0-5][0-9]|5079[0-5][0-9]|50796[0-4]))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "visa",
                PriorityOver = new string[] { "gpn", "interpayment", "instapayment" },
                RegexpBin = new Regex(@"^(4|6367)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{13,19}$)(?:4|6367)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "gpn",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(1946|50|56|58|6[0-3])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:1946|50|56|58|6[0-3])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "maestro",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^((?:50|5[6-9]|6[0-9]))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{12,19}$)(?:(?:50|5[6-9]|6[0-9]))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
        };
    }
}
