// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-11T19:24:36.731Z

using System;
using System.Text.RegularExpressions;

namespace CreditCardIdentifier
{
    /// <summary>
    /// Credit card brand data.
    /// </summary>
    public static class BrandData
    {
        /// <summary>
        /// Brand definition.
        /// </summary>
        public class Brand
        {
            public string Name { get; set; }
            public string[] PriorityOver { get; set; }
            public Regex RegexpBin { get; set; }
            public Regex RegexpFull { get; set; }
            public Regex RegexpCvv { get; set; }
        }

        /// <summary>
        /// All supported credit card brands.
        /// </summary>
        public static readonly Brand[] Brands = new Brand[]
        {
            new Brand
            {
                Name = "amex",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(3[47])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{15}$)(?:3[47])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{4}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "diners",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(3(?:0[0-5]|[68][0-9]))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{14}$)(?:3(?:0[0-5]|[68][0-9]))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "elo",
                PriorityOver = new string[] { "visa", "aura", "discover", "banesecard" },
                RegexpBin = new Regex(@"^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "jcb",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^((?:2131|1800|35))", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "mastercard",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(5[1-5]|2[2-7][0-2][0-9])", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:5[1-5]|2[2-7][0-2][0-9])[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "aura",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(50)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:50)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "banesecard",
                PriorityOver = new string[] { "discover" },
                RegexpBin = new Regex(@"^(636117|637473|637470|637472|650725|650046|650591|651668|651679)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "visa",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(4|6367)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{13,16}$)(?:4|6367)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "discover",
                PriorityOver = new string[] { "hipercard" },
                RegexpBin = new Regex(@"^(6011|622|64|65)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16}$)(?:6011|622|64|65)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{4}$", RegexOptions.Compiled),
            },
            new Brand
            {
                Name = "hipercard",
                PriorityOver = Array.Empty<string>(),
                RegexpBin = new Regex(@"^(38|60)", RegexOptions.Compiled),
                RegexpFull = new Regex(@"^(?=.{16,19}$)(?:38|60)[0-9]*$", RegexOptions.Compiled),
                RegexpCvv = new Regex(@"^\d{3}$", RegexOptions.Compiled),
            },
        };
    }
}
