// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-12T09:52:15.508Z

using System;
using System.Collections.Generic;

namespace CreditCardIdentifier
{
    /// <summary>
    /// Credit card brand data (detailed).
    /// </summary>
    public static class BrandDataDetailed
    {
        /// <summary>
        /// Number validation info
        /// </summary>
        public class NumberInfo
        {
            public int[] Lengths { get; set; }
            public bool Luhn { get; set; }
        }

        /// <summary>
        /// CVV validation info
        /// </summary>
        public class CvvInfo
        {
            public int Length { get; set; }
        }

        /// <summary>
        /// Pattern info
        /// </summary>
        public class Pattern
        {
            public string Bin { get; set; }
            public int[] Length { get; set; }
            public bool Luhn { get; set; }
            public int CvvLength { get; set; }
        }

        /// <summary>
        /// BIN info
        /// </summary>
        public class BinInfo
        {
            public string Bin { get; set; }
            public string Type { get; set; }
            public string Category { get; set; }
            public string Issuer { get; set; }
            public string[] Countries { get; set; }
        }

        /// <summary>
        /// Detailed brand info
        /// </summary>
        public class Brand
        {
            public string Scheme { get; set; }
            public string BrandName { get; set; }
            public string Type { get; set; }
            public NumberInfo Number { get; set; }
            public CvvInfo Cvv { get; set; }
            public Pattern[] Patterns { get; set; }
            public string[] Countries { get; set; }
            public Dictionary<string, object> Metadata { get; set; }
            public string[] PriorityOver { get; set; }
            public BinInfo[] Bins { get; set; }
        }

        /// <summary>
        /// All detailed brand data
        /// </summary>
        public static readonly Brand[] Brands = new Brand[]
        {
            new Brand
            {
                Scheme = "amex",
                BrandName = "American Express",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 15 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 4
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^3[47]",
                        Length = new int[] { 15 },
                        Luhn = true,
                        CvvLength = 4
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "amex.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "diners",
                BrandName = "Diners Club",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 14 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^3(?:0[0-5]|[68][0-9])",
                        Length = new int[] { 14 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "diners.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "elo",
                BrandName = "Elo",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^401178|^401179|^431274|^438935|^451416|^457393|^457631|^457632|^504175",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^627780|^636297|^636368",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(506699|5067[0-6]\\d|50677[0-8])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^65003[1-3]",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65003[5-9]|65004\\d|65005[0-1])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65040[5-9]|6504[1-3]\\d)",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65054[1-9]|6505[5-8]\\d|65059[0-8])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65070\\d|65071[0-8])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6507(2[0-7])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6509[0-9]",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65165[2-9]|6516[6-7]\\d)",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65500\\d|65501\\d)",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^(65502[1-9]|6550[3-4]\\d|65505[0-8])",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "BR" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "elo.json" } },
                PriorityOver = new string[] { "visa", "aura", "discover", "banesecard" },
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "jcb",
                BrandName = "JCB",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^(?:2131|1800|35)",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "jcb.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "mastercard",
                BrandName = "Mastercard",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^5[1-5]",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^2[2-7][0-2][0-9]",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "mastercard.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "aura",
                BrandName = "Aura",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16, 17, 18, 19 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^50",
                        Length = new int[] { 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "BR" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "aura.json" } },
                PriorityOver = new string[] { "maestro" },
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "banesecard",
                BrandName = "BaneseCard",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^636117",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^637473",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^637470",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^637472",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^650725",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^650046",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^650591",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^651668",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^651679",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "BR" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "banesecard.json" } },
                PriorityOver = new string[] { "discover" },
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "maestro",
                BrandName = "Maestro",
                Type = "debit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^5018",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^5020",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^5038",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^5893",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6304",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6759",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^676[1-3]",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6706",
                        Length = new int[] { 12, 13, 14, 15, 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "maestro.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "visa",
                BrandName = "Visa",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 13, 16 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^4",
                        Length = new int[] { 13, 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^6367",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", new object[] { "visa/base.json", "visa/bins-br-1.json", "visa/bins-br-2.json" } } },
                PriorityOver = Array.Empty<string>(),
                Bins = new BinInfo[]
                {
                    new BinInfo
                    {
                        Bin = "491441",
                        Type = "CREDIT",
                        Category = "",
                        Issuer = "BANCO PROSPER, S.A.",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491440",
                        Type = "CREDIT",
                        Category = "",
                        Issuer = "BANCO PROSPER, S.A.",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491439",
                        Type = "CREDIT",
                        Category = "",
                        Issuer = "BANCO PROSPER, S.A.",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491423",
                        Type = "CREDIT",
                        Category = "",
                        Issuer = "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491416",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO DO ESTADO DO PARANA",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491415",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO DO ESTADO DO PARANA",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491414",
                        Type = "CREDIT",
                        Category = "GOLD",
                        Issuer = "BANCO DO ESTADO DO PARANA",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491413",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                        Countries = new string[] { "BR" }
                    },
                    new BinInfo
                    {
                        Bin = "491412",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491411",
                        Type = "CREDIT",
                        Category = "GOLD",
                        Issuer = "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491402",
                        Type = "CREDIT",
                        Category = "",
                        Issuer = "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491316",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO SANTANDER BRASIL, S.A.",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491315",
                        Type = "CREDIT",
                        Category = "CLASSIC",
                        Issuer = "BANCO SANTANDER, S.A.",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491314",
                        Type = "CREDIT",
                        Category = "GOLD",
                        Issuer = "BANCO SANTANDER, S.A.",
                        Countries = Array.Empty<string>()
                    },
                    new BinInfo
                    {
                        Bin = "491256",
                        Type = "CREDIT",
                        Category = "PLATINUM",
                        Issuer = "BANCO PANAMERICANO, S.A.",
                        Countries = Array.Empty<string>()
                    },
                }
            },
            new Brand
            {
                Scheme = "discover",
                BrandName = "Discover",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16, 19 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^6011",
                        Length = new int[] { 16, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^64[4-9]",
                        Length = new int[] { 16, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^65",
                        Length = new int[] { 16, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "US" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "discover.json" } },
                PriorityOver = new string[] { "hipercard", "unionpay" },
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "hipercard",
                BrandName = "Hipercard",
                Type = "credit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16, 19 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^38",
                        Length = new int[] { 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                    new Pattern
                    {
                        Bin = "^60",
                        Length = new int[] { 16 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "BR" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "hipercard.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
            new Brand
            {
                Scheme = "unionpay",
                BrandName = "UnionPay",
                Type = "debit",
                Number = new NumberInfo
                {
                    Lengths = new int[] { 16, 17, 18, 19 },
                    Luhn = true
                },
                Cvv = new CvvInfo
                {
                    Length = 3
                },
                Patterns = new Pattern[]
                {
                    new Pattern
                    {
                        Bin = "^62",
                        Length = new int[] { 16, 17, 18, 19 },
                        Luhn = true,
                        CvvLength = 3
                    },
                },
                Countries = new string[] { "CN", "GLOBAL" },
                Metadata = new Dictionary<string, object> { { "sourceFile", "unionpay.json" } },
                PriorityOver = Array.Empty<string>(),
                Bins = Array.Empty<BinInfo>()
            },
        };
    }
}
