# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-15T00:50:32.482Z

defmodule CreditcardIdentifier.DataDetailed do
  @moduledoc """
  Credit card brand data (detailed).
  Loads bins from JSON at runtime to handle large data efficiently.
  """

  @json_path Path.join(:code.priv_dir(:creditcard_identifier), "cards-detailed.json")

  @doc """
  Returns all credit card brands (detailed).
  Data is lazy-loaded from JSON file.
  """
  @spec brands() :: [map()]
  def brands do
    case :persistent_term.get(__MODULE__, nil) do
      nil ->
        data = load_from_json()
        :persistent_term.put(__MODULE__, data)
        data
      data ->
        data
    end
  end

  defp load_from_json do
    @json_path
    |> File.read!()
    |> Jason.decode!(keys: :atoms)
  end
end
