'use strict';

/**
 * Code generators for native data files in each language
 */

/**
 * Generate JavaScript/TypeScript native data file
 */
function generateJavaScript(brands) {
  const lines = [
    '// Auto-generated by bin-cc build - DO NOT EDIT',
    `// Generated: ${new Date().toISOString()}`,
    "'use strict';",
    '',
    '/**',
    ' * Credit card brand data',
    ' * @type {Array<{name: string, priority: number, priorityOver: string[], regexpBin: string, regexpFull: string, regexpCvv: string}>}',
    ' */',
    'const brands = ['
  ];

  for (const brand of brands) {
    lines.push('  {');
    lines.push(`    name: ${JSON.stringify(brand.name)},`);
    lines.push(`    priorityOver: ${JSON.stringify(brand.priorityOver || [])},`);
    lines.push(`    regexpBin: ${JSON.stringify(brand.regexpBin)},`);
    lines.push(`    regexpFull: ${JSON.stringify(brand.regexpFull)},`);
    lines.push(`    regexpCvv: ${JSON.stringify(brand.regexpCvv)},`);
    lines.push('  },');
  }

  lines.push('];');
  lines.push('');
  lines.push('module.exports = brands;');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate TypeScript declaration file
 */
function generateTypeScriptDeclaration() {
  return `// Auto-generated by bin-cc build - DO NOT EDIT

export interface Brand {
  name: string;
  priorityOver: string[];
  regexpBin: string;
  regexpFull: string;
  regexpCvv: string;
}

declare const brands: Brand[];
export = brands;
`;
}

/**
 * Generate Python native data file
 */
function generatePython(brands) {
  const lines = [
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '"""Credit card brand data."""',
    '',
    'from typing import List, TypedDict',
    '',
    '',
    'class Brand(TypedDict):',
    '    """Brand definition."""',
    '    name: str',
    '    priority_over: List[str]',
    '    regexp_bin: str',
    '    regexp_full: str',
    '    regexp_cvv: str',
    '',
    '',
    'BRANDS: List[Brand] = ['
  ];

  for (const brand of brands) {
    lines.push('    {');
    lines.push(`        "name": ${JSON.stringify(brand.name)},`);
    lines.push(`        "priority_over": ${JSON.stringify(brand.priorityOver || [])},`);
    lines.push(`        "regexp_bin": ${pythonString(brand.regexpBin)},`);
    lines.push(`        "regexp_full": ${pythonString(brand.regexpFull)},`);
    lines.push(`        "regexp_cvv": ${pythonString(brand.regexpCvv)},`);
    lines.push('    },');
  }

  lines.push(']');
  lines.push('');

  return lines.join('\n');
}

/**
 * Convert string to Python raw string for regex
 */
function pythonString(str) {
  // Use raw string for regex patterns
  if (str.includes('\\')) {
    return `r"${str}"`;
  }
  return JSON.stringify(str);
}

/**
 * Generate Ruby native data file
 */
function generateRuby(brands) {
  const lines = [
    '# frozen_string_literal: true',
    '',
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'module CreditcardIdentifier',
    '  # Credit card brand data',
    '  BRANDS = ['
  ];

  for (const brand of brands) {
    lines.push('    {');
    lines.push(`      name: ${JSON.stringify(brand.name)},`);
    lines.push(`      priority_over: ${JSON.stringify(brand.priorityOver || [])},`);
    lines.push(`      regexp_bin: ${rubyRegex(brand.regexpBin)},`);
    lines.push(`      regexp_full: ${rubyRegex(brand.regexpFull)},`);
    lines.push(`      regexp_cvv: ${rubyRegex(brand.regexpCvv)},`);
    lines.push('    },');
  }

  lines.push('  ].freeze');
  lines.push('end');
  lines.push('');

  return lines.join('\n');
}

/**
 * Convert regex string to Ruby Regexp literal
 */
function rubyRegex(str) {
  // Ruby regex literals use /pattern/
  return `/${str.replace(/^\^/, '\\A').replace(/\$$/, '\\z')}/`;
}

/**
 * Generate Elixir native data file
 */
function generateElixir(brands) {
  const lines = [
    '# Auto-generated by bin-cc build - DO NOT EDIT',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'defmodule CreditcardIdentifier.Data do',
    '  @moduledoc """',
    '  Credit card brand data.',
    '  """',
    '',
    '  @brands ['
  ];

  for (const brand of brands) {
    lines.push('    %{');
    lines.push(`      name: ${JSON.stringify(brand.name)},`);
    lines.push(`      priority_over: ${JSON.stringify(brand.priorityOver || [])},`);
    lines.push(`      regexp_bin: ~r/${escapeElixirRegex(brand.regexpBin)}/,`);
    lines.push(`      regexp_full: ~r/${escapeElixirRegex(brand.regexpFull)}/,`);
    lines.push(`      regexp_cvv: ~r/${escapeElixirRegex(brand.regexpCvv)}/`);
    lines.push('    },');
  }

  lines.push('  ]');
  lines.push('');
  lines.push('  @doc """');
  lines.push('  Returns all credit card brands.');
  lines.push('  """');
  lines.push('  @spec brands() :: [map()]');
  lines.push('  def brands, do: @brands');
  lines.push('end');
  lines.push('');

  return lines.join('\n');
}

/**
 * Escape regex for Elixir sigil
 */
function escapeElixirRegex(str) {
  return str.replace(/\//g, '\\/');
}

/**
 * Generate C# native data file
 */
function generateCSharp(brands) {
  const lines = [
    '// Auto-generated by bin-cc build - DO NOT EDIT',
    `// Generated: ${new Date().toISOString()}`,
    '',
    'using System.Text.RegularExpressions;',
    '',
    'namespace CreditCardIdentifier',
    '{',
    '    /// <summary>',
    '    /// Credit card brand data.',
    '    /// </summary>',
    '    public static class BrandData',
    '    {',
    '        /// <summary>',
    '        /// Brand definition.',
    '        /// </summary>',
    '        public class Brand',
    '        {',
    '            public string Name { get; set; }',
    '            public string[] PriorityOver { get; set; }',
    '            public Regex RegexpBin { get; set; }',
    '            public Regex RegexpFull { get; set; }',
    '            public Regex RegexpCvv { get; set; }',
    '        }',
    '',
    '        /// <summary>',
    '        /// All supported credit card brands.',
    '        /// </summary>',
    '        public static readonly Brand[] Brands = new Brand[]',
    '        {'
  ];

  for (const brand of brands) {
    lines.push('            new Brand');
    lines.push('            {');
    lines.push(`                Name = ${JSON.stringify(brand.name)},`);
    lines.push(`                PriorityOver = new[] { ${(brand.priorityOver || []).map(s => JSON.stringify(s)).join(', ')} },`);
    lines.push(`                RegexpBin = new Regex(@"${escapeVerbatim(brand.regexpBin)}", RegexOptions.Compiled),`);
    lines.push(`                RegexpFull = new Regex(@"${escapeVerbatim(brand.regexpFull)}", RegexOptions.Compiled),`);
    lines.push(`                RegexpCvv = new Regex(@"${escapeVerbatim(brand.regexpCvv)}", RegexOptions.Compiled),`);
    lines.push('            },');
  }

  lines.push('        };');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Escape string for C# verbatim string literal
 */
function escapeVerbatim(str) {
  return str.replace(/"/g, '""');
}

module.exports = {
  generateJavaScript,
  generateTypeScriptDeclaration,
  generatePython,
  generateRuby,
  generateElixir,
  generateCSharp
};
