// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-11T23:10:33.990Z

use std::collections::HashMap;

/// Credit card brand data (detailed).

#[derive(Debug, Clone)]
pub struct Pattern {
    pub bin: &'static str,
    pub length: Vec<i32>,
    pub luhn: bool,
    pub cvv_length: i32,
}

#[derive(Debug, Clone)]
pub struct Bin {
    pub bin: &'static str,
    pub bin_type: &'static str,
    pub category: &'static str,
    pub issuer: &'static str,
    pub countries: Vec<&'static str>,
}

#[derive(Debug, Clone)]
pub struct BrandDetailed {
    pub scheme: &'static str,
    pub brand: &'static str,
    pub brand_type: &'static str,
    pub number_lengths: Vec<i32>,
    pub number_luhn: bool,
    pub cvv_length: i32,
    pub patterns: Vec<Pattern>,
    pub countries: Vec<&'static str>,
    pub priority_over: Vec<&'static str>,
    pub bins: Vec<Bin>,
}

pub static BRANDS: &[BrandDetailed] = &[
    BrandDetailed {
        scheme: "amex",
        brand: "American Express",
        brand_type: "credit",
        number_lengths: vec![15],
        number_luhn: true,
        cvv_length: 4,
        patterns: vec![
            Pattern {
                bin: "^3[47]",
                length: vec![15],
                luhn: true,
                cvv_length: 4,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "diners",
        brand: "Diners Club",
        brand_type: "credit",
        number_lengths: vec![14],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^3(?:0[0-5]|[68][0-9])",
                length: vec![14],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "elo",
        brand: "Elo",
        brand_type: "credit",
        number_lengths: vec![16],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^401178|^401179|^431274|^438935|^451416|^457393|^457631|^457632|^504175",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^627780|^636297|^636368",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(506699|5067[0-6]\\d|50677[0-8])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^65003[1-3]",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65003[5-9]|65004\\d|65005[0-1])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65040[5-9]|6504[1-3]\\d)",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65054[1-9]|6505[5-8]\\d|65059[0-8])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65070\\d|65071[0-8])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6507(2[0-7])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6509[0-9]",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65165[2-9]|6516[6-7]\\d)",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65500\\d|65501\\d)",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^(65502[1-9]|6550[3-4]\\d|65505[0-8])",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["BR"],
        priority_over: vec!["visa", "aura", "discover", "banesecard"],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "jcb",
        brand: "JCB",
        brand_type: "credit",
        number_lengths: vec![16],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^(?:2131|1800|35)",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "mastercard",
        brand: "Mastercard",
        brand_type: "credit",
        number_lengths: vec![16],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^5[1-5]",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^2[2-7][0-2][0-9]",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "aura",
        brand: "Aura",
        brand_type: "credit",
        number_lengths: vec![16, 17, 18, 19],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^50",
                length: vec![16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["BR"],
        priority_over: vec!["maestro"],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "banesecard",
        brand: "BaneseCard",
        brand_type: "credit",
        number_lengths: vec![16],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^636117",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^637473",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^637470",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^637472",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^650725",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^650046",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^650591",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^651668",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^651679",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["BR"],
        priority_over: vec!["discover"],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "maestro",
        brand: "Maestro",
        brand_type: "debit",
        number_lengths: vec![12, 13, 14, 15, 16, 17, 18, 19],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^5018",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^5020",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^5038",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^5893",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6304",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6759",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^676[1-3]",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6706",
                length: vec![12, 13, 14, 15, 16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "visa",
        brand: "Visa",
        brand_type: "credit",
        number_lengths: vec![13, 16],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^4",
                length: vec![13, 16],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^6367",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["GLOBAL"],
        priority_over: vec![],
        bins: vec![
            Bin {
                bin: "491441",
                bin_type: "CREDIT",
                category: "",
                issuer: "BANCO PROSPER, S.A.",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491440",
                bin_type: "CREDIT",
                category: "",
                issuer: "BANCO PROSPER, S.A.",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491439",
                bin_type: "CREDIT",
                category: "",
                issuer: "BANCO PROSPER, S.A.",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491423",
                bin_type: "CREDIT",
                category: "",
                issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491416",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO DO ESTADO DO PARANA",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491415",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO DO ESTADO DO PARANA",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491414",
                bin_type: "CREDIT",
                category: "GOLD",
                issuer: "BANCO DO ESTADO DO PARANA",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491413",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                countries: vec!["BR"],
            },
            Bin {
                bin: "491412",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                countries: vec![],
            },
            Bin {
                bin: "491411",
                bin_type: "CREDIT",
                category: "GOLD",
                issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S/A",
                countries: vec![],
            },
            Bin {
                bin: "491402",
                bin_type: "CREDIT",
                category: "",
                issuer: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL S.A.)",
                countries: vec![],
            },
            Bin {
                bin: "491316",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO SANTANDER BRASIL, S.A.",
                countries: vec![],
            },
            Bin {
                bin: "491315",
                bin_type: "CREDIT",
                category: "CLASSIC",
                issuer: "BANCO SANTANDER, S.A.",
                countries: vec![],
            },
            Bin {
                bin: "491314",
                bin_type: "CREDIT",
                category: "GOLD",
                issuer: "BANCO SANTANDER, S.A.",
                countries: vec![],
            },
            Bin {
                bin: "491256",
                bin_type: "CREDIT",
                category: "PLATINUM",
                issuer: "BANCO PANAMERICANO, S.A.",
                countries: vec![],
            },
        ],
    },
    BrandDetailed {
        scheme: "discover",
        brand: "Discover",
        brand_type: "credit",
        number_lengths: vec![16, 19],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^6011",
                length: vec![16, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^64[4-9]",
                length: vec![16, 19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^65",
                length: vec![16, 19],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["US"],
        priority_over: vec!["hipercard", "unionpay"],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "hipercard",
        brand: "Hipercard",
        brand_type: "credit",
        number_lengths: vec![16, 19],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^38",
                length: vec![19],
                luhn: true,
                cvv_length: 3,
            },
            Pattern {
                bin: "^60",
                length: vec![16],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["BR"],
        priority_over: vec![],
        bins: vec![
        ],
    },
    BrandDetailed {
        scheme: "unionpay",
        brand: "UnionPay",
        brand_type: "debit",
        number_lengths: vec![16, 17, 18, 19],
        number_luhn: true,
        cvv_length: 3,
        patterns: vec![
            Pattern {
                bin: "^62",
                length: vec![16, 17, 18, 19],
                luhn: true,
                cvv_length: 3,
            },
        ],
        countries: vec!["CN", "GLOBAL"],
        priority_over: vec![],
        bins: vec![
        ],
    },
];
