// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-15T00:50:32.622Z

//! Credit card brand data (detailed).
//! Loads bins from JSON at runtime to handle large data efficiently.

use serde::Deserialize;
use std::sync::OnceLock;

const CARDS_DETAILED_JSON: &str = include_str!("cards-detailed.json");

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Pattern {
    pub bin: String,
    pub length: Vec<i32>,
    pub luhn: bool,
    pub cvv_length: i32,
}

#[derive(Debug, Clone, Deserialize)]
pub struct BinInfo {
    pub bin: String,
    #[serde(rename = "type")]
    pub bin_type: Option<String>,
    pub category: Option<String>,
    pub issuer: Option<String>,
    pub countries: Option<Vec<String>>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NumberInfo {
    pub lengths: Vec<i32>,
    pub luhn: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CvvInfo {
    pub length: i32,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BrandDetailed {
    pub scheme: String,
    pub brand: String,
    #[serde(rename = "type")]
    pub brand_type: Option<String>,
    pub number: NumberInfo,
    pub cvv: CvvInfo,
    pub patterns: Vec<Pattern>,
    pub countries: Vec<String>,
    #[serde(default)]
    pub priority_over: Vec<String>,
    #[serde(default)]
    pub bins: Vec<BinInfo>,
}

static BRANDS_CACHE: OnceLock<Vec<BrandDetailed>> = OnceLock::new();

/// Get detailed brand data (lazy-loaded from JSON).
pub fn get_brands() -> &'static [BrandDetailed] {
    BRANDS_CACHE.get_or_init(|| {
        serde_json::from_str(CARDS_DETAILED_JSON)
            .expect("Failed to parse cards-detailed.json")
    })
}

/// Deprecated: Use get_brands() instead.
#[deprecated(note = "Use get_brands() instead")]
pub static BRANDS: &[BrandDetailed] = &[];
