#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { COMPILED_DIR, CARDS_FILE, DETAILED_FILE, BRANDS_MD_FILE, CONFLICTS_FILE, LIBS_DIR } = require('./lib/config');
const { readAllSources } = require('./lib/source-reader');
const { toDetailedFormat, toSimplifiedFormat } = require('./lib/transformers');
const { validateSources, validateCompiled } = require('./validate');
const {
  generateJavaScript,
  generateTypeScriptDeclaration,
  generatePython,
  generateRuby,
  generateElixir,
  generateCSharp
} = require('./lib/generators');

/**
 * Ensure output directory exists
 */
function ensureOutputDir() {
  if (!fs.existsSync(COMPILED_DIR)) {
    fs.mkdirSync(COMPILED_DIR, { recursive: true });
  }
}

/**
 * Generate native data files for all libraries
 */
function generateNativeFiles(simplified) {
  console.log('\n📦 Generating native data files...');
  
  // JavaScript
  const jsDataDir = path.join(LIBS_DIR, 'javascript', 'data');
  fs.mkdirSync(jsDataDir, { recursive: true });
  fs.writeFileSync(path.join(jsDataDir, 'brands.js'), generateJavaScript(simplified));
  fs.writeFileSync(path.join(jsDataDir, 'brands.d.ts'), generateTypeScriptDeclaration());
  console.log('  ✓ Generated libs/javascript/data/brands.js');
  
  // Python
  const pyDataDir = path.join(LIBS_DIR, 'python', 'creditcard_identifier');
  fs.mkdirSync(pyDataDir, { recursive: true });
  fs.writeFileSync(path.join(pyDataDir, 'brands.py'), generatePython(simplified));
  console.log('  ✓ Generated libs/python/creditcard_identifier/brands.py');
  
  // Ruby
  const rbLibDir = path.join(LIBS_DIR, 'ruby', 'lib');
  fs.mkdirSync(rbLibDir, { recursive: true });
  fs.writeFileSync(path.join(rbLibDir, 'creditcard_identifier', 'brands.rb'), generateRuby(simplified));
  console.log('  ✓ Generated libs/ruby/lib/creditcard_identifier/brands.rb');
  
  // Elixir
  const exLibDir = path.join(LIBS_DIR, 'elixir', 'lib');
  fs.mkdirSync(exLibDir, { recursive: true });
  fs.writeFileSync(path.join(exLibDir, 'creditcard_identifier', 'data.ex'), generateElixir(simplified));
  console.log('  ✓ Generated libs/elixir/lib/creditcard_identifier/data.ex');
  
  // C#
  const csDir = path.join(LIBS_DIR, 'dotnet', 'CreditCardIdentifier');
  fs.mkdirSync(csDir, { recursive: true });
  fs.writeFileSync(path.join(csDir, 'BrandData.cs'), generateCSharp(simplified));
  console.log('  ✓ Generated libs/dotnet/CreditCardIdentifier/BrandData.cs');
}

/**
 * Write JSON file
 */
function writeJson(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

/**
 * Generate markdown table of supported brands
 */
function generateBrandsMd(detailed) {
  const lines = [
    '# Supported Card Brands',
    '',
    'This file is auto-generated by `npm run build`.',
    '',
    '| Brand | Starts with | Lengths | CVV | Official |',
    '| ----- | ----------- | ------- | --- | -------- |'
  ];

  for (const card of detailed) {
    const bins = card.patterns.map(p => p.bin.replace(/^\^/, '').replace(/\[.*?\]/g, 'X')).join(', ');
    const lengths = card.number.lengths.join(', ');
    const official = card.unofficial ? '❌' : '✅';
    lines.push(`| ${card.brand} | ${bins} | ${lengths} | ${card.cvv.length} | ${official} |`);
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Sort brands based on priorityOver relationships
 * If A has priorityOver: ["B"], then A comes before B
 */
function sortByPriority(items, getScheme, getPriorityOver) {
  // Build a map of scheme -> items that should come before it
  const mustComeBefore = new Map(); // scheme -> Set of schemes that must come before it
  
  for (const item of items) {
    const scheme = getScheme(item);
    const priorityOver = getPriorityOver(item) || [];
    
    for (const other of priorityOver) {
      if (!mustComeBefore.has(other)) {
        mustComeBefore.set(other, new Set());
      }
      mustComeBefore.get(other).add(scheme);
    }
  }
  
  // Sort: items with no dependencies first, then by how many depend on them
  return [...items].sort((a, b) => {
    const schemeA = getScheme(a);
    const schemeB = getScheme(b);
    
    // Check if A must come before B
    const bDeps = mustComeBefore.get(schemeB) || new Set();
    if (bDeps.has(schemeA)) return -1;
    
    // Check if B must come before A
    const aDeps = mustComeBefore.get(schemeA) || new Set();
    if (aDeps.has(schemeB)) return 1;
    
    // No direct relationship - sort by number of schemes that depend on them
    const aScore = mustComeBefore.get(schemeA)?.size || 0;
    const bScore = mustComeBefore.get(schemeB)?.size || 0;
    
    // More dependencies = more general = should come later
    return aScore - bScore;
  });
}

/**
 * Build compiled data from sources
 */
function build() {
  console.log('🔨 Building bin-cc data...\n');

  ensureOutputDir();

  const sources = readAllSources();
  let detailed = [];
  let simplified = [];

  for (const { source, schemeName, sourceFiles } of sources) {
    console.log(`  ✓ Processing ${source.brand} (${schemeName})`);

    detailed.push(toDetailedFormat(source, schemeName, sourceFiles));
    simplified.push(toSimplifiedFormat(source, schemeName));
  }

  // Sort by priorityOver relationships - more specific patterns first
  detailed = sortByPriority(detailed, d => d.scheme, d => d.priorityOver);
  simplified = sortByPriority(simplified, s => s.name, s => s.priorityOver);

  writeJson(DETAILED_FILE, detailed);
  console.log(`\n✅ Detailed data written to: ${path.relative(process.cwd(), DETAILED_FILE)}`);

  writeJson(CARDS_FILE, simplified);
  console.log(`✅ Simplified data written to: ${path.relative(process.cwd(), CARDS_FILE)}`);

  fs.writeFileSync(BRANDS_MD_FILE, generateBrandsMd(detailed));
  console.log(`✅ Brands markdown written to: ${path.relative(process.cwd(), BRANDS_MD_FILE)}`);

  console.log(`\n📊 Statistics:`);
  console.log(`   Total brands: ${detailed.length}`);

  // Generate native data files for each language
  generateNativeFiles(simplified);

  return { detailed, simplified };
}

// CLI execution
if (require.main === module) {
  try {
    console.log('');

    // Validate sources first
    if (!validateSources()) {
      console.error('\n❌ Build aborted due to validation errors\n');
      process.exit(1);
    }

    // Build
    const { detailed } = build();

    // Validate compiled output
    const { valid, conflicts } = validateCompiled(detailed);
    
    // Write conflicts to file
    if (conflicts && conflicts.length > 0) {
      writeJson(CONFLICTS_FILE, {
        generated: new Date().toISOString(),
        total: conflicts.length,
        conflicts
      });
      console.log(`⚠️  Conflicts written to: ${path.relative(process.cwd(), CONFLICTS_FILE)}`);
    }
    
    if (!valid) {
      console.error('\n❌ Build produced invalid output\n');
      process.exit(1);
    }

    console.log('\n✨ Build completed successfully!\n');
  } catch (error) {
    console.error('\n❌ Build failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

module.exports = { build };
