#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { COMPILED_DIR, CARDS_FILE, DETAILED_FILE, BRANDS_MD_FILE } = require('./lib/config');
const { readAllSources } = require('./lib/source-reader');
const { toDetailedFormat, toSimplifiedFormat } = require('./lib/transformers');
const { validateSources, validateCompiled } = require('./validate');

/**
 * Ensure output directory exists
 */
function ensureOutputDir() {
  if (!fs.existsSync(COMPILED_DIR)) {
    fs.mkdirSync(COMPILED_DIR, { recursive: true });
  }
}

/**
 * Write JSON file
 */
function writeJson(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

/**
 * Generate markdown table of supported brands
 */
function generateBrandsMd(detailed) {
  const lines = [
    '# Supported Card Brands',
    '',
    'This file is auto-generated by `npm run build`.',
    '',
    '| Brand | Starts with | Lengths | CVV | Official |',
    '| ----- | ----------- | ------- | --- | -------- |'
  ];

  for (const card of detailed) {
    const bins = card.patterns.map(p => p.bin.replace(/^\^/, '').replace(/\[.*?\]/g, 'X')).join(', ');
    const lengths = card.number.lengths.join(', ');
    const official = card.unofficial ? '❌' : '✅';
    lines.push(`| ${card.brand} | ${bins} | ${lengths} | ${card.cvv.length} | ${official} |`);
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Build compiled data from sources
 */
function build() {
  console.log('🔨 Building bin-cc data...\n');

  ensureOutputDir();

  const sources = readAllSources();
  const detailed = [];
  const simplified = [];

  for (const { source, schemeName, sourceFiles } of sources) {
    console.log(`  ✓ Processing ${source.brand} (${schemeName})`);

    detailed.push(toDetailedFormat(source, schemeName, sourceFiles));
    simplified.push(toSimplifiedFormat(source, schemeName));
  }

  writeJson(DETAILED_FILE, detailed);
  console.log(`\n✅ Detailed data written to: ${path.relative(process.cwd(), DETAILED_FILE)}`);

  writeJson(CARDS_FILE, simplified);
  console.log(`✅ Simplified data written to: ${path.relative(process.cwd(), CARDS_FILE)}`);

  fs.writeFileSync(BRANDS_MD_FILE, generateBrandsMd(detailed));
  console.log(`✅ Brands markdown written to: ${path.relative(process.cwd(), BRANDS_MD_FILE)}`);

  console.log(`\n📊 Statistics:`);
  console.log(`   Total brands: ${detailed.length}`);

  return { detailed, simplified };
}

// CLI execution
if (require.main === module) {
  try {
    console.log('');

    // Validate sources first
    if (!validateSources()) {
      console.error('\n❌ Build aborted due to validation errors\n');
      process.exit(1);
    }

    // Build
    const { detailed } = build();

    // Validate compiled output
    if (!validateCompiled(detailed)) {
      console.error('\n❌ Build produced invalid output\n');
      process.exit(1);
    }

    console.log('\n✨ Build completed successfully!\n');
  } catch (error) {
    console.error('\n❌ Build failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

module.exports = { build };
