# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-15T00:50:32.386Z
"""Credit card brand data (detailed). Loads bins from JSON at runtime."""

import json
import os
from typing import Any, Dict, List


def _load_json() -> List[Dict[str, Any]]:
    """Load detailed brand data from JSON file."""
    json_path = os.path.join(os.path.dirname(__file__), "cards-detailed.json")
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


# Lazy-loaded brands data
_brands_cache: List[Dict[str, Any]] = []


def get_brands() -> List[Dict[str, Any]]:
    """Get detailed brand data (lazy-loaded from JSON)."""
    global _brands_cache
    if not _brands_cache:
        _brands_cache = _load_json()
    return _brands_cache


# Module-level lazy property for backwards compatibility
class _BrandsProxy(list):
    """Proxy that loads data on first access."""
    _loaded = False

    def _ensure_loaded(self):
        if not self._loaded:
            self.extend(get_brands())
            self._loaded = True

    def __iter__(self):
        self._ensure_loaded()
        return super().__iter__()

    def __len__(self):
        self._ensure_loaded()
        return super().__len__()

    def __getitem__(self, key):
        self._ensure_loaded()
        return super().__getitem__(key)


BRANDS = _BrandsProxy()
