# Auto-generated by bin-cc build - DO NOT EDIT
# Generated: 2026-01-14T23:27:22.656Z
"""Credit card brand data."""

from typing import List, TypedDict


class Brand(TypedDict):
    """Brand definition."""
    name: str
    priority_over: List[str]
    regexp_bin: str
    regexp_full: str
    regexp_cvv: str


BRANDS: List[Brand] = [
    {
        "name": "amex",
        "priority_over": [],
        "regexp_bin": "^(3[47])",
        "regexp_full": "^(?=.{15}$)(?:3[47])[0-9]*$",
        "regexp_cvv": r"^\d{4}$",
    },
    {
        "name": "bankcard",
        "priority_over": [],
        "regexp_bin": "^(5610|56022[1-5])",
        "regexp_full": "^(?=.{16}$)(?:5610|56022[1-5])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "cabal",
        "priority_over": ["maestro"],
        "regexp_bin": "^(604400|627170|603522|589657|(60420[1-9]|6042[1][0-9])|(6043[0-9]{2}))",
        "regexp_full": "^(?=.{16}$)(?:604400|627170|603522|589657|(60420[1-9]|6042[1][0-9])|(6043[0-9]{2}))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "china-t-union",
        "priority_over": [],
        "regexp_bin": "^(31)",
        "regexp_full": "^(?=.{19}$)(?:31)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "dankort",
        "priority_over": ["visa"],
        "regexp_bin": "^(5019|4571)",
        "regexp_full": "^(?=.{16}$)(?:5019|4571)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "diners-enroute",
        "priority_over": [],
        "regexp_bin": "^(2014|2149)",
        "regexp_full": "^(?=.{15}$)(?:2014|2149)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "elo",
        "priority_over": ["visa", "aura", "discover", "banesecard"],
        "regexp_bin": r"^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))",
        "regexp_full": r"^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\d|50677[0-8])|(50900\d|5090[1-9]\d|509[1-9]\d{2})|65003[1-3]|(65003[5-9]|65004\d|65005[0-1])|(65040[5-9]|6504[1-3]\d)|(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])|(65054[1-9]|6505[5-8]\d|65059[0-8])|(65070\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\d)|(65500\d|65501\d)|(65502[1-9]|6550[3-4]\d|65505[0-8]))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "humo",
        "priority_over": [],
        "regexp_bin": "^(9860)",
        "regexp_full": "^(?=.{16}$)(?:9860)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "lankapay",
        "priority_over": ["jcb"],
        "regexp_bin": "^(357111)",
        "regexp_full": "^(?=.{16}$)(?:357111)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "laser",
        "priority_over": ["maestro"],
        "regexp_bin": "^(6304|6706|6771|6709)",
        "regexp_full": "^(?=.{16,19}$)(?:6304|6706|6771|6709)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "mastercard",
        "priority_over": ["diners-us-canada", "mir", "borica"],
        "regexp_bin": "^(5[1-5]|2(?:2(?:2[1-9]|[3-9][0-9])|[3-6][0-9]{2}|7(?:[0-1][0-9]|20)))",
        "regexp_full": "^(?=.{16}$)(?:5[1-5]|2(?:2(?:2[1-9]|[3-9][0-9])|[3-6][0-9]{2}|7(?:[0-1][0-9]|20)))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "napas",
        "priority_over": [],
        "regexp_bin": "^(9704)",
        "regexp_full": "^(?=.{16,19}$)(?:9704)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "naranja",
        "priority_over": [],
        "regexp_bin": "^(589562)",
        "regexp_full": "^(?=.{16}$)(?:589562)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "nps-pridnestrovie",
        "priority_over": [],
        "regexp_bin": "^(605474[0-4])",
        "regexp_full": "^(?=.{16}$)(?:605474[0-4])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "solo",
        "priority_over": [],
        "regexp_bin": "^(6334|6767)",
        "regexp_full": "^(?=.{16,19}$)(?:6334|6767)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "switch",
        "priority_over": ["visa", "maestro"],
        "regexp_bin": "^(4903|4905|4911|4936|564182|633110|6333|6759)",
        "regexp_full": "^(?=.{16,19}$)(?:4903|4905|4911|4936|564182|633110|6333|6759)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "uatp",
        "priority_over": [],
        "regexp_bin": "^(1)",
        "regexp_full": "^(?=.{15}$)(?:1)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "ukrcart",
        "priority_over": ["hipercard"],
        "regexp_bin": "^((60400[1-9][0-9]{2}|6040[1-9][0-9]{3}|604[1][0-9]{4}|6042[0][0][0-9]{2}))",
        "regexp_full": "^(?=.{16,19}$)(?:(60400[1-9][0-9]{2}|6040[1-9][0-9]{3}|604[1][0-9]{4}|6042[0][0][0-9]{2}))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "uzcard",
        "priority_over": [],
        "regexp_bin": "^(8600|5614)",
        "regexp_full": "^(?=.{16}$)(?:8600|5614)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "visa-electron",
        "priority_over": ["visa"],
        "regexp_bin": "^(4026|4405|4508|4844|4913|4917|417500)",
        "regexp_full": "^(?=.{16}$)(?:4026|4405|4508|4844|4913|4917|417500)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "banesecard",
        "priority_over": ["discover"],
        "regexp_bin": "^(636117|637473|637470|637472|650725|650046|650591|651668|651679)",
        "regexp_full": "^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "borica",
        "priority_over": [],
        "regexp_bin": "^(2205)",
        "regexp_full": "^(?=.{16}$)(?:2205)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "diners",
        "priority_over": [],
        "regexp_bin": "^(3(?:0[0-5]|6|8|9))",
        "regexp_full": "^(?=.{14}$)(?:3(?:0[0-5]|6|8|9))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "instapayment",
        "priority_over": [],
        "regexp_bin": "^(63[7-9])",
        "regexp_full": "^(?=.{16}$)(?:63[7-9])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "interpayment",
        "priority_over": [],
        "regexp_bin": "^(636)",
        "regexp_full": "^(?=.{16,19}$)(?:636)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "jcb",
        "priority_over": [],
        "regexp_bin": "^((?:2131|1800|35))",
        "regexp_full": "^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "mir",
        "priority_over": [],
        "regexp_bin": "^(220[0-4])",
        "regexp_full": "^(?=.{16,19}$)(?:220[0-4])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "troy",
        "priority_over": [],
        "regexp_bin": "^(65|9792)",
        "regexp_full": "^(?=.{16}$)(?:65|9792)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "aura",
        "priority_over": ["maestro", "maestro-uk", "gpn", "verve"],
        "regexp_bin": "^(50)",
        "regexp_full": "^(?=.{16,19}$)(?:50)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "maestro-uk",
        "priority_over": ["maestro"],
        "regexp_bin": "^(6759|676770|676774)",
        "regexp_full": "^(?=.{12,19}$)(?:6759|676770|676774)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "discover",
        "priority_over": ["hipercard", "unionpay", "gpn", "rupay", "troy", "verve"],
        "regexp_bin": "^(6011|64[4-9]|65)",
        "regexp_full": "^(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "unionpay",
        "priority_over": [],
        "regexp_bin": "^(62)",
        "regexp_full": "^(?=.{16,19}$)(?:62)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "hipercard",
        "priority_over": ["gpn", "diners", "diners-international", "rupay"],
        "regexp_bin": "^(384|60)",
        "regexp_full": "^(?=.{16,19}$)(?:384|60)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "rupay",
        "priority_over": [],
        "regexp_bin": "^(60|65|8[12]|508|35[36])",
        "regexp_full": "^(?=.{16}$)(?:60|65|8[12]|508|35[36])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "verve",
        "priority_over": ["discover", "aura"],
        "regexp_bin": "^((5060[9][9]|506[1][0-9]{2}|5061[0-9][0-8])|(65000[2-9]|6500[1][0-9]|6500[2][0-7])|(5078[6-9][5-9]|507[89][0-5][0-9]|5079[0-5][0-9]|50796[0-4]))",
        "regexp_full": "^(?=.{16,19}$)(?:(5060[9][9]|506[1][0-9]{2}|5061[0-9][0-8])|(65000[2-9]|6500[1][0-9]|6500[2][0-7])|(5078[6-9][5-9]|507[89][0-5][0-9]|5079[0-5][0-9]|50796[0-4]))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "visa",
        "priority_over": ["gpn", "interpayment", "instapayment"],
        "regexp_bin": "^(4|6367)",
        "regexp_full": "^(?=.{13,19}$)(?:4|6367)[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "gpn",
        "priority_over": [],
        "regexp_bin": "^(1946|50|56|58|6[0-3])",
        "regexp_full": "^(?=.{16,19}$)(?:1946|50|56|58|6[0-3])[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
    {
        "name": "maestro",
        "priority_over": [],
        "regexp_bin": "^((?:50|5[6-9]|6[0-9]))",
        "regexp_full": "^(?=.{12,19}$)(?:(?:50|5[6-9]|6[0-9]))[0-9]*$",
        "regexp_cvv": r"^\d{3}$",
    },
]
