<?php
// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-15T00:50:32.716Z

namespace CreditCard\Identifier;

/**
 * Credit card brand data (detailed).
 * Loads bins from JSON at runtime to handle large data efficiently.
 */
class BrandDataDetailed
{
    private static ?array $brandsCache = null;

    /**
     * Get all detailed brand data (lazy-loaded from JSON).
     * @return array<array>
     */
    public static function getBrands(): array
    {
        if (self::$brandsCache === null) {
            self::$brandsCache = self::loadFromJson();
        }
        return self::$brandsCache;
    }

    private static function loadFromJson(): array
    {
        $jsonPath = __DIR__ . '/cards-detailed.json';
        $json = file_get_contents($jsonPath);
        if ($json === false) {
            throw new \RuntimeException('Failed to read cards-detailed.json');
        }
        $data = json_decode($json, true);
        if ($data === null) {
            throw new \RuntimeException('Failed to parse cards-detailed.json');
        }
        return $data;
    }
}
