<?php
// Auto-generated by bin-cc build - DO NOT EDIT
// Generated: 2026-01-11T23:02:34.895Z

namespace CreditCard\Identifier;

/**
 * Credit card brand data (simplified).
 */
class BrandData
{
    /**
     * @return array<array{name: string, priorityOver: array<string>, regexpBin: string, regexpFull: string, regexpCvv: string}>
     */
    public static function getBrands(): array
    {
        return [
            [
                'name' => 'amex',
                'priorityOver' => [],
                'regexpBin' => '^(3[47])',
                'regexpFull' => '^(?=.{15}$)(?:3[47])[0-9]*$',
                'regexpCvv' => '^\\d{4}$',
            ],
            [
                'name' => 'diners',
                'priorityOver' => [],
                'regexpBin' => '^(3(?:0[0-5]|[68][0-9]))',
                'regexpFull' => '^(?=.{14}$)(?:3(?:0[0-5]|[68][0-9]))[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'elo',
                'priorityOver' => ['visa', 'aura', 'discover', 'banesecard'],
                'regexpBin' => '^(401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))',
                'regexpFull' => '^(?=.{16}$)(?:401178|401179|431274|438935|451416|457393|457631|457632|504175|627780|636297|636368|(506699|5067[0-6]\\d|50677[0-8])|(50900\\d|5090[1-9]\\d|509[1-9]\\d{2})|65003[1-3]|(65003[5-9]|65004\\d|65005[0-1])|(65040[5-9]|6504[1-3]\\d)|(65048[5-9]|65049\\d|6505[0-2]\\d|65053[0-8])|(65054[1-9]|6505[5-8]\\d|65059[0-8])|(65070\\d|65071[0-8])|6507(2[0-7])|6509[0-9]|(65165[2-9]|6516[6-7]\\d)|(65500\\d|65501\\d)|(65502[1-9]|6550[3-4]\\d|65505[0-8]))[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'jcb',
                'priorityOver' => [],
                'regexpBin' => '^((?:2131|1800|35))',
                'regexpFull' => '^(?=.{16}$)(?:(?:2131|1800|35))[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'mastercard',
                'priorityOver' => [],
                'regexpBin' => '^(5[1-5]|2[2-7][0-2][0-9])',
                'regexpFull' => '^(?=.{16}$)(?:5[1-5]|2[2-7][0-2][0-9])[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'aura',
                'priorityOver' => ['maestro'],
                'regexpBin' => '^(50)',
                'regexpFull' => '^(?=.{16,19}$)(?:50)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'banesecard',
                'priorityOver' => ['discover'],
                'regexpBin' => '^(636117|637473|637470|637472|650725|650046|650591|651668|651679)',
                'regexpFull' => '^(?=.{16}$)(?:636117|637473|637470|637472|650725|650046|650591|651668|651679)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'maestro',
                'priorityOver' => [],
                'regexpBin' => '^(5018|5020|5038|5893|6304|6759|676[1-3]|6706)',
                'regexpFull' => '^(?=.{12,19}$)(?:5018|5020|5038|5893|6304|6759|676[1-3]|6706)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'visa',
                'priorityOver' => [],
                'regexpBin' => '^(4|6367)',
                'regexpFull' => '^(?=.{13,16}$)(?:4|6367)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'discover',
                'priorityOver' => ['hipercard', 'unionpay'],
                'regexpBin' => '^(6011|64[4-9]|65)',
                'regexpFull' => '^(?=.{16,19}$)(?:6011|64[4-9]|65)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'hipercard',
                'priorityOver' => [],
                'regexpBin' => '^(38|60)',
                'regexpFull' => '^(?=.{16,19}$)(?:38|60)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
            [
                'name' => 'unionpay',
                'priorityOver' => [],
                'regexpBin' => '^(62)',
                'regexpFull' => '^(?=.{16,19}$)(?:62)[0-9]*$',
                'regexpCvv' => '^\\d{3}$',
            ],
        ];
    }
}
